### ISSUE TITLE
BooleanQuery Occur::MustNot causes no docs to be matched

### ISSUE THREAD

**Issue by shikhar** [quickwit-inc/tantivy#1153]
**Describe the bug**
- What did you do?
Searched with a `BooleanQuery` with a `MustNot` occurrence.

- What happened?
No documents mached.

- What was expected?
Documented behaviour of only excluding documents matching `MustNot` clause.

**Which version of tantivy are you using?**
0.16.1

**To Reproduce**

I was seeing `MustNot` causing no documents to be returned when used as part of a `BooleanQuery` with other `Must` occurrences.

Wrote a minimal test case which does fail: https://gist.github.com/shikhar/775f34ecf80a7fd4db2b62a5b830383c

```diff
diff --git a/src/query/boolean_query/boolean_query.rs b/src/query/boolean_query/boolean_query.rs
index 513c81027..f15e46030 100644
--- a/src/query/boolean_query/boolean_query.rs
+++ b/src/query/boolean_query/boolean_query.rs
@@ -206,6 +206,8 @@ impl BooleanQuery {
 
 #[cfg(test)]
 mod tests {
+    use tantivy_query_grammar::Occur;
+
     use super::BooleanQuery;
     use crate::collector::DocSetCollector;
     use crate::query::{QueryClone, TermQuery};
@@ -226,6 +228,25 @@ mod tests {
         Ok(index)
     }
 
+    #[test]
+    fn test_must_not() -> crate::Result<()> {
+        let index = create_test_index()?;
+        let searcher = index.reader()?.searcher();
+        let text = index.schema().get_field("text").unwrap();
+        let term_a = TermQuery::new(Term::from_field_text(text, "a"), IndexRecordOption::Basic).box_clone();
+        let not_a = BooleanQuery::new(vec![(Occur::MustNot, term_a)]);
+        let docs = searcher.search(&not_a, &DocSetCollector)?;
+        assert_eq!(
+            docs,
+            vec![
+                DocAddress::new(0u32, 0u32),
+            ]
+            .into_iter()
+            .collect()
+        );
+        Ok(())
+    }
+
     #[test]
     fn test_union() -> crate::Result<()> {
         let index = create_test_index()?;
```

```
---- query::boolean_query::boolean_query::tests::test_must_not stdout ----
thread 'query::boolean_query::boolean_query::tests::test_must_not' panicked at 'assertion failed: `(left == right)`
  left: `{}`,
 right: `{DocAddress { segment_ord: 0, doc_id: 0 }}`', src/query/boolean_query/boolean_query.rs:239:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    query::boolean_query::boolean_query::tests::test_must_not

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 500 filtered out; finished in 0.02s
```

**Comment by shikhar** [comment]
Maybe I'm missing something? I found this assertion https://github.com/tantivy-search/tantivy/blob/46b86a797651e1d09dc9859ee4db705272e6cfa7/src/query/boolean_query/mod.rs#L164-L167

But I would expect docs [0,1,2] to match that https://github.com/tantivy-search/tantivy/blob/46b86a797651e1d09dc9859ee4db705272e6cfa7/src/query/boolean_query/mod.rs#L36-L40

**Comment by fulmicoton** [comment]
In the issue description you mentioned "with other Must Occurrences". Your unit test only has one MustNot occurrence.
The following works ok for me.
```
#[test]
    fn test_must_not() -> crate::Result<()> {
        let index = create_test_index()?;
        let searcher = index.reader()?.searcher();
        let text = index.schema().get_field("text").unwrap();
        let term_a = TermQuery::new(Term::from_field_text(text, "a"), IndexRecordOption::Basic).box_clone();
        let term_d = TermQuery::new(Term::from_field_text(text, "d"), IndexRecordOption::Basic).box_clone();
        let a_but_not_d = BooleanQuery::new(vec![(Occur::Must, term_a), (Occur::MustNot, term_d)]);
        let docs = searcher.search(&a_but_not_d, &DocSetCollector)?;
        assert_eq!(
            docs,
            vec![
                DocAddress::new(0u32, 1u32),
                DocAddress::new(0u32, 2u32),
            ]
            .into_iter()
            .collect()
        );
        Ok(())
    }
```

For the example, you joined, what you should expect is non trivial at all.
It is a bit similar to the question, should empty query return no elements or all documents... And this is something that depends on your application.

In tantivy, (-term_A) is interpreted as (emptyset - term_A).
You can get the resultset you are shooting for by using the AllQuery.

**Comment by shikhar** [comment]
I see, indeed doing an intersection with the `AllQuery` gives me what I had expected in these test cases.

Yes this test case is different from my app, where introducing `MustNot` clauses is causing no documents to be returned even though there are other types of occurrences. I will poke around a bit more on that, probably a bug in my usage!

Thanks for the explanation.

**Comment by shikhar** [comment]
> no documents to be returned even though there are other types of occurrences

It was actually:

```
BooleanQuery {
    Must BooleanQuery { Should .... },
    Must BooleanQuery {
       Must QueryA
       Must BooleanQuery { MustNot QueryB }
    },
}
```

I'm seeing the expected results after turning this into:

```
BooleanQuery {
    Must BooleanQuery { Should .... },
    Must BooleanQuery {
       Must QueryA
       MustNot QueryB
    },
}
```

Thanks again!

**Comment by fulmicoton** [comment]
Sweet!
