### ISSUE TITLE
thread 'merge_thread3' panicked at range start index 16380 out of range for slice of length 5850

### ISSUE THREAD

**Issue by derek-zhou** [quickwit-inc/tantivy#1158]
**Describe the bug**
I am using tantivy as part of my application; and every once in a while I am seeing:

thread 'merge_thread3' panicked at 'range start index 16380 out of range for slice of length 5850', /home/debian/.cargo/registry/src/github.com-1ecc6299db9ec823/tantivy-0.15.0/src/store/reader.rs:212:35

In my log file. Nothing catastrophic happened though.  I am using tantivy 0.15.0. I think it has something to do with the data in my current database so it is probably hard to reproduce else where. Is this something I need to worry about?

**Comment by fulmicoton** [comment]
Yes. Tantivy 0.15 contains several major bugs.

0.15.3 on the other hand, has no known bugs.
At this point however your index might be corrupted.

(0.16.1 is also another good option to consider, but the index format is incompatible.)

**Comment by derek-zhou** [comment]
Thanks. Can you point me to the potential bugs? I don't want to rebuild by index.

**Comment by derek-zhou** [comment]
I found the bug description. So, if I am willing to rebuild my index, should I stick to 0.15.3 or upgrade to 0.16.1?

**Comment by fulmicoton** [comment]
I'd go for 0.16.1

**Comment by derek-zhou** [comment]
Thanks. Running 0.16.1 now. So far so good.
