### ISSUE TITLE
Remove panic if flush is forbidden when dropping a RAMDirectory write

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/tantivy#1185]
While this check has proved itself very helpful, people want to use the RAMDirectory for production usage, and panicking 
is not a good idea there.

We need to at least disable the logic.
Indeed, if a write returns an io::Error, it makes sense to not flush and drop the writer.

**Comment by manuel-woelker** [comment]
I think this one was fixed in https://github.com/quickwit-oss/tantivy/commit/c6b5ab1dbe9374c6d3442c8259f576ab47405eb6

Or is there anything else left to do?

**Comment by fulmicoton** [comment]
Correct! Thx
