### ISSUE TITLE
Possible to compile to webassembly and run in the browser?

### ISSUE THREAD

**Issue by crisdosaygo** [quickwit-inc/tantivy#1193]
I'm interested in providing a full text search engine in JavaScript

**Comment by fulmicoton** [comment]
@i5ik I don't understand what you mean by "product 22120"

**Comment by crisdosaygo** [comment]
@fulmicoton that's OK you don't need to to answer the question. If you let me know you're confused about anything else I'll try to help you out!

**Comment by fulmicoton** [comment]
What do you mean by "product 22120"?

**Comment by i5ik** [comment]
@fulmicoton heh, no worries, I can try helping you out with that for sure! So, I removed the reference that confused you. And I can close this and maybe open a fresh issue if needed to fully cleanse of this, if that seems better!

**Comment by crisdosaygo** [comment]
@fulmicoton If you'd rather not engage with this question, I totally get it! That's why I'm asking you, I'd rather not try to do this on my own either...webassembly can be tricky and I don't know anything about rust or it. Tho I am sorry for you that you felt confused about this today, that was not my intention to bring that to you. Hmm, how can I make this better for you? 

Well first, I'll just say hope you feel better soon, and have a great rest of your day you absolute legend! Second I've edited my question to remove the reference that confused you (and which I didn't intent to include but only did in response to your 'please be as specific as possible with your use case' issue template I saw when I started) and third I've closed this question as I don't want to give you more than you can handle, I know how tough it is being an open source maintainer and how important is it to say 'no' and prioritize, and I'm sure you must be super busy. I'm sorry I brought this to you on your bad day. And fourth, I've added a fresh issue that avoids any references and just focuses on the question. Definitely close that tho if this is too much for you to handle right now, I totally get it, no worries! And if you feel like getting to either of these at some point in the future definitely feel free to reopen and ping me about. 

Anyway, best of luck with it all and I LOVE :heart: what you are trying to do with tantivy. It is SO awesome! Thank you so much, and have a good one. And hey if you're ever in Hong Kong or Taipei in the next 3 months let me know, I can grab a coffee with you for real!!!! :P ;) xxx

**Comment by fulmicoton** [comment]
There seems to be a big misunderstanding here. I just wanted to know what "product 22120" .
It is necessary for me to know a little bit about the background for this kind of question.

Back to the question.

Search can work in Web Assembly without too much trouble.
Indexing on the other requires threading. Adapting tantivy to work in WASM would require too much work.

**Comment by fmassot** [comment]
A good example of tantivy (only search) running in the browser can be found here: https://github.com/quickwit-inc/tantivy/pull/1067
