### ISSUE TITLE
Sort top docs ASC

### ISSUE THREAD

**Issue by lavrd** [quickwit-inc/tantivy#1206]
Hello, I want to sort  top docs ASC not DESC. How can I do it? I didn't find how to do it in lib docs.
As I understand `order_by_u64_field` can sort only DESC.

There is my code https://github.com/lavrxxx/loghell/tree/master/prototype-rs.

**Comment by fulmicoton** [comment]
You can use custom score, open your fast field reader and emit a `std::cmp::Reverse(your_field)`

See 
https://docs.rs/tantivy/0.16.1/tantivy/collector/struct.TopDocs.html#method.custom_score

for the documentation of custom_score.

**Comment by lavrd** [comment]
Thank you very much for help!
I'll leave it here, maybe it will be useful to someone else.
```rust
    let id = index.schema().get_field("id").expect("failed to get id field");
    let top_docs_order_by_id_asc = TopDocs
    ::with_limit(10).and_offset(0)
        .custom_score(move |segment_reader: &SegmentReader| {
            let id_reader = segment_reader.fast_fields().u64(id).unwrap();
            move |doc: DocId| {
                let id: u64 = id_reader.get(doc);
                std::cmp::Reverse(id)
            }
        });
    let top_docs = searcher.search(&query, &top_docs_order_by_id_asc)?;
```

**Comment by fulmicoton** [comment]
Awesome thank you @lavrxxx
