### ISSUE TITLE
Remove tantivy schema strictness

### ISSUE THREAD

**Issue by PSeitz** [quickwit-inc/tantivy#1211]
Currently all fields in the data need to be defined in the tantivy schema, even if these fields should be ignored.
This can be an issue if you have a dataset with many fields and are interested in only few fields.

On the other side fields can be missing in the data while indexing, so there is some asymmetry.

For that I would propose to remove the strict schema default in tantivy and simply ignore fields which are not defined. It will also provide a lower entry barrier for new users (e.g. just indexing one field as a poke test).

**Comment by fulmicoton** [comment]
I agree with this !
