### ISSUE TITLE
Check and fix doc.rs pages

### ISSUE THREAD

**Issue by evanxg852000** [quickwit-inc/tantivy#1232]
Right now the documentation page for `https://docs.rs/tantivy/latest/tantivy/termdict/type.TermDictionary.html` renders almost empty without listing methods and other item info. This could be the case for other types as well.

This task is to check the documentation rendered at  https://docs.rs/tantivy/latest/tantivy and fix pages that are not rendering documentation content.

**Comment by saroh** [comment]
by public modules in the tantivy crate: 
- [x] tantivy https://github.com/quickwit-oss/tantivy/pull/1391
- [x] aggregation #1299 
- [x] collector #1247 
- [x] directory #1247 
- [x] error #1299 
- [x] fastfield #1301 
- [x] fieldnorm
- [x] merge_policy
- [x] positions https://github.com/quickwit-oss/tantivy/pull/1391
- [x] postings https://github.com/quickwit-oss/tantivy/pull/1391
- [x] query https://github.com/quickwit-oss/tantivy/pull/1391
- [x] schema https://github.com/quickwit-oss/tantivy/pull/1391
- [x] space_usage https://github.com/quickwit-oss/tantivy/pull/1391
- [x] store https://github.com/quickwit-oss/tantivy/pull/1391
- [x] termdict #1242 
- [x] tokenizer https://github.com/quickwit-oss/tantivy/pull/1391
