### ISSUE TITLE
can't create a custom MergePolicy, because part of the signature is in a private module

### ISSUE THREAD

**Issue by kmitchener** [quickwit-inc/tantivy#1235]
**Describe the bug**
Attempt to create a custom MergePolicy, but it requires you to return a MergeCandidate which is private.

**Which version of tantivy are you using?**
0.16.1

**To Reproduce**
Try to create a custom MergePolicy.

~~~~
error[E0603]: module `indexer` is private
   --> src\lib.rs:71:82
    |
71  |     fn compute_merge_candidates(&self, segments: &[SegmentMeta]) -> Vec<tantivy::indexer::merge_policy::MergeCandidate> {
    |                                                                                  ^^^^^^^ private module
    |
~~~~

If your bug is deterministic, can you give a minimal reproducing code?
Some bugs are not deterministic. Can you describe with precision in which context it happened?
If this is possible, can you share your code?

**Comment by fulmicoton** [comment]
Thank you for the report!
