### ISSUE TITLE
BM25 MoreLikeThis

### ISSUE THREAD

**Issue by stevemk14ebr** [quickwit-inc/tantivy#1259]
**Is your feature request related to a problem? Please describe.**
Feature Request. The MoreLikeThisQuery currently exists to find documents similar to a given document, and it uses tf-idf. BM25 appears to be a potentially better scoring system for a generic query like this. Lucene uses tf-idf for their MoreLikeThisQuery, perhaps tantivy could improve on this? There is already a bm25 implementation within this library so hopefully the transition wouldn't be too hard.

**Describe the solution you'd like**
Discussion and potential switch to BM25.

**[Optional] describe alternatives you've considered**
The feature request itself is optional

**Comment by fulmicoton** [comment]
Is this something you actually need?

**Comment by stevemk14ebr** [comment]
The document scores are much better with BM25 for my use case. I am avoiding MoreLikeThis because of this, so yes in a way.

In my current scheme I take a starting document and then filter the features down to those I've decided are interesting based on occurrence count globally, then do a large OR query like: term1 OR term2 OR term3 OR .... The search uses BM25 for scoring, and I get great results like this. And what I can do is take the highest scoring document, and divide all other scores by that value, and this gives me a very rough percentage similar. Typically the highest document has a value around 400 - 700.

MoreLikeThis is basically the same thing as what I am doing custom, but it doesn't use the BM25 scoring and the returned values break my scoring system.

**Comment by fulmicoton** [comment]
@stevemk14ebr Let's do this then!
Do you want to make the change?

**Comment by stevemk14ebr** [comment]
I don't really understand the internals of this library enough to do that confidently :/

**Comment by stevemk14ebr** [comment]
Looking at this more I think this is actually not needed? The MoreLikeThis seems to use tf-idf to sort and filter the fields that are used to build the boolean query, but the boolean query itself is executed via the normal search apis which I _think_ use BM-25, is that correct? If this is true my issue is with how I attempt to normalize scores afterwards to be approximate %'s, rather than with the scoring mechanism of MoreLikeThis itself.

**Comment by fulmicoton** [comment]
That would be a question for @evanxg852000

**Comment by evanxg852000** [comment]
@stevemk14ebr currently `tf-idf` is used for scoring the terms retrieved from the provided document. Then we use these term/scoring to compose a query. The resulting query is just executed like other queries therefore on document scoring. I think `tf-idf` is fine for terms scoring. 
Does this yield search results far from your expectation (number of outliers)?

**Comment by stevemk14ebr** [comment]
I think that confirms the query scores returned are from bm-25 then and therefore this issue can be closed
