### ISSUE TITLE
Why is the order of the documents unstable?

### ISSUE THREAD

**Issue by BlackGlory** [quickwit-inc/tantivy#1284]
I was writing integration tests for a project that uses tantivy,
and I noticed that writes in the same order produced different sequential results after commit,
which actually broke my test cases...

code:
```rust
writer.add_document(doc1);
writer.add_document(doc2);
writer.commit().unwrap();

let searcher = reader.searcher();
println!("{:?}", schema.to_named_doc(&searcher.doc(DocAddress::new(0, 0)).unwrap()));
println!("{:?}", schema.to_named_doc(&searcher.doc(DocAddress::new(1, 0)).unwrap()));
```

output:
```
// case 1
NamedFieldDocument({"_id": [Str("1")], "text": [Str("hello world")]})
NamedFieldDocument({"_id": [Str("2")], "text": [Str("bye world")]})

// case 2
NamedFieldDocument({"_id": [Str("2")], "text": [Str("bye world")]})
NamedFieldDocument({"_id": [Str("1")], "text": [Str("hello world")]})
```

The output seems random, is there a reason for this?

**Comment by fulmicoton** [comment]
Multithreading. By default tantivy uses more than one thread for indexing. It is not necessarily a good idea.

You can create a single threaded writer to avoid that.
I forgot the name of the method in Index.

**Comment by BlackGlory** [comment]
Thanks, using [writer_with_num_threads](https://docs.rs/tantivy/0.16.1/tantivy/struct.Index.html#method.writer_with_num_threads) does solve this.
