### ISSUE TITLE
Document that dates are truncated at the second precision.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/tantivy#1287]

**Comment by waywardmonkeys** [comment]
This was changed in a4be239d to have microseconds duration and it looks like the docs reflect this.

@fulmicoton This can probably be closed.

**Comment by waywardmonkeys** [comment]
Looks like #1396 and #1408 are related.

**Comment by fulmicoton** [comment]
Nice catch @waywardmonkeys
