### ISSUE TITLE
query_parser::UnknownTokenizer error message should swap "tokenizer" and "field"

### ISSUE THREAD

**Issue by iiibui** [quickwit-inc/tantivy#1303]
`UnknownTokenizer` defined:
https://github.com/quickwit-oss/tantivy/blob/6656a70d1b1d88600fee993c371fdece0cf4caa9/src/query/query_parser/query_parser.rs#L62-L63
but used:
https://github.com/quickwit-oss/tantivy/blob/6656a70d1b1d88600fee993c371fdece0cf4caa9/src/query/query_parser/query_parser.rs#L344-L347

https://github.com/quickwit-oss/tantivy/blob/6656a70d1b1d88600fee993c371fdece0cf4caa9/src/query/query_parser/query_parser.rs#L421-L424

https://github.com/quickwit-oss/tantivy/blob/6656a70d1b1d88600fee993c371fdece0cf4caa9/src/query/query_parser/query_parser.rs#L446-L449

**Comment by fulmicoton** [comment]
Thanks for reporting.
We should no use positional arguments here. 

@PSeitz can you have a look?
