### ISSUE TITLE
Questions about general purpose search

### ISSUE THREAD

**Issue by ericmackrodt** [quickwit-inc/tantivy#1322]
Hi,
I'm asking this here because I didn't know where to ask, feel free to close it if if is the wrong place.
I have a website which is a general purpose search engine for finding old websites.

I currently use Postgres with its full-text search functionality with an index table with over 3 million records. This table will probably reach 4 to 5 million records eventually but I don't think it's gonna pass that.
So at some point I will never have to ingest any data again.

This is working okay, but I think I could have better performance and search result quality with a tool like Tantivy, so here are my questions:

My service is hosted in a VPS with 1gb of ram and 1 core. It's what I can afford at the moment. Would the resource usage from Tantivy be lower than Postgres? I don't need the searches to happen under 50ms, if they take 1 to 2 seconds because the search is being done in the SSD, it's okay.

In that one table, I have records in multiple languages, since Postgres TS_VECTOR columns are language unaware, I can generate the TS_VECTOR in any language, write that to the table and filter by the ts_vector and the language column when doing a search. Would I be able to have multiple languages in one index in Tantivy with the ability to search only for that language taking in consideration the particular characteristics of that language?

I use Hunspell because the default stem dictionaries in Postgres can return wrong results, like for example, if I search for 'Animal', I get results for 'Anime', 'Animation' and so on. With Hunspell that's fixed and I wonder if Tantivy has something similar, ideally out of the box, but if not, easy to install for the languages it supports.

Are stop words for all the default languages configured by default? Postgres comes with that built-in.

Finally, an issue I still have with Postgres is that, if a stop-word is a very relevant part of a search query, it's taken away. For example, if I try to search for "Doctor Who", I'm actually searching for "Doctor", if I try to search for "The Sims", I'm actually searching for "Sims", If I try to search for "The Who"... Well, I'm searching for nothing there. So, is there a way to make a stop-word stop being a stop word in certain cases where they are actually an integral part of the search term?

Those are all of my questions, thanks in advance for the help.
Let me know if there's a better place to ask these.

**Comment by fulmicoton** [comment]
> My service is hosted in a VPS with 1gb of ram and 1 core. It's what I can afford at the moment. Would the resource usage from Tantivy be lower than Postgres? I don't need the searches to happen under 50ms, if they take 1 to 2 seconds because the search is being done in the SSD, it's okay.

Yes. It won't take much and your search will return in less than 50ms provided your queries are not too pathological.

> Would I be able to have multiple languages in one index in Tantivy with the ability to search only for that language taking in consideration the particular characteristics of that language?

Depending on the languages you want to support, you might have to do some extra footwork.
For instance Japanese requires a specific tokenizer. Tantivy ships that, but it requires you to have one field per language.
 
> I use Hunspell because the default stem dictionaries in Postgres can return wrong results, like for example, if I search for 'Animal', I get results for 'Anime', 'Animation' and so on. With Hunspell that's fixed and I wonder if Tantivy has something similar, ideally out of the box, but if not, easy to install for the languages it supports.

Tantivy ships a snowball stemmer. Again that is something that you will have to configure per field.

> Finally, an issue I still have with Postgres is that, if a stop-word is a very relevant part of a search query, it's taken away. For example, if I try to search for "Doctor Who", I'm actually searching for "Doctor", if I try to search for "The Sims", I'm actually searching for "Sims", If I try to search for "The Who"... Well, I'm searching for nothing there. So, is there a way to make a stop-word stop being a stop word in certain cases where they are actually an integral part of the search term?

That is something you configure. I tend to prefer keeping stop words.

**Comment by fulmicoton** [comment]
> I'm asking this here because I didn't know where to ask, feel free to close it if if is the wrong place.
I have a website which is a general purpose search engine for finding old websites.

Opening a github issue is great.
The discord chat is a good place too, especially if you are not entirely sure how to phrase your questions as the discussion can be interactive.

**Comment by ericmackrodt** [comment]
Hi @fulmicoton , Thanks for getting back to me so quickly.
I'll also join the discord.

What do you mean by different fields? Would my document have to have a field for english, one for portuguese, one for italian and so on and if, say, a record is in english, the other ones will be undefined?

I do want to keep stop words, I just want to make exceptions for when the stop word is super relevant for the query.

Are there pre-made lists that I can use with the snowball stemmer to solve the Animal/Animation/Anime issue?

Thanks again for the help!

**Comment by fulmicoton** [comment]
> What do you mean by different fields? Would my document have to have a field for english, one for portuguese, one for italian and so on and if, say, a record is in english, the other ones will be undefined?

Yes.

> Are there pre-made lists that I can use with the snowball stemmer to solve the Animal/Animation/Anime issue?

There are no such pre-made lists. You would have to implement your own `TokenFilter`.
Alternatively. You could index both with and without stemming and rely on ranking to show you the most relevant results first.
That's yet another field though.

**Comment by ericmackrodt** [comment]
Awesome! Thanks @fulmicoton , this was super helpful!
