### ISSUE TITLE
Add ability to extract identified word and surrounding sentence

### ISSUE THREAD

**Issue by danielhstahl** [quickwit-inc/tantivy#1327]
**Is your feature request related to a problem? Please describe.**
When I get the result of a search, I'd like to know which part of my search was matched (eg, in a query "hello world" OR "goodbye" I'd like the search to tell me if it matched "hello world" or "goodbye").  I'd also like to get the sentence that the matched phrase comes from.
**Describe the solution you'd like**
While I'm not sure if the solution is possible, specifying that the returned items should include the sentence and the matched phrase as a "get_field".  Eg, "get_field("match")" or "get_field("containing_sentence")".  
**[Optional] describe alternatives you've considered**
Instead of adding an entire "body" to the index, add sentences one by one.  I have concerns this would slow both the indexing and the search for documents.

**Comment by fulmicoton** [comment]
For knowing the terms that matched, Query::explain should give you that information (and more)
https://docs.rs/tantivy/latest/tantivy/query/trait.Query.html#method.explain

tantivy also has a functionality called snippets; https://github.com/quickwit-oss/tantivy/blob/main/examples/snippet.rs
It somehow answers the second part of your problem.

This is not *exactly* what you asked for however.
You can also code both functionality outside of tantivy.

**Comment by danielhstahl** [comment]
oh perfect!   I hadn't seen the snippet example.  That addresses my request.
