### ISSUE TITLE
Is there a better way to near real time search

### ISSUE THREAD

**Issue by naaive** [quickwit-inc/tantivy#1330]
currentyly i commit intervaly, but it's often high cpu on mac m1.

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/73341653/162107839-beef3789-a636-42f0-970d-90114e1828ef.png">
<img width="2413" alt="image" src="https://user-images.githubusercontent.com/73341653/162109076-1c459aaf-1ce9-4112-b2e4-bec9587dd6a0.png">

Is there a better way to near real time search? thanks.

**Comment by fulmicoton** [comment]
I see a lot of threads. How many segments do you have?
tantivy does not include any backpressure mechanism if you commit too often.

You can easily end up with merges not keeping up with your commits, and have massive amount of segments, which will in turn have an horrible impact both on search and on commit times when commit contains deletes.

**Comment by PSeitz** [comment]
I think the best way to support near real time search is to be able to include search on uncommitted data, which is not supported in tantivy right now and can also be quite tricky to support the same featureset.

A specialized [MergePolicy](https://docs.rs/tantivy/latest/tantivy/merge_policy/trait.MergePolicy.html) for that scenario could also help. (and maybe include a backpressure mechanism?)

On the other side, we can try to improve performance for that scenario to enable a higher commit interval.
Do you also delete docuemnts? Most of the time is spent in `compute_delete_bitset`.

**Comment by naaive** [comment]
@fulmicoton @PSeitz 

For better indexing performance, i used NoMergePolicy, this is the main reason why so many segments and threads. now i disable the NoMergePolicy and use default policy. cpu and disk usage become low now! thanks for your help!
