### ISSUE TITLE
Support Date type in Aggregation

### ISSUE THREAD

**Issue by PSeitz** [quickwit-inc/tantivy#1332]
Currently the Date type is filtered as valid fast field type, but this may be overly strict.

**Comment by PSeitz** [comment]
Elasticsearch behavior on date fields. On a histogram, the date is formatted in a separate field `key_as_string`. The date is formatted according to the fields mapping `format`.

## Problem

We don't store the date format in tantivy. Where do we get the format information from. 

1. Store it in the tantivy schema
2. Provide it in the aggregation request
3. Don't return `key_as_string` from tantivy
4. Provide an empty `key_as_string` in the returned struct that can be post-processed


## Elasticsearch Example


 "key_as_string" : "2015-01-01T00:00:00.000Z",

```json

PUT datetest
{
  "mappings": {
    "properties": {
      "date": {
        "type": "date",
        "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"
      }
    }
  }
}

PUT datetest/_doc/1
{ "date": "2015-01-01" } 
PUT datetest/_doc/2
{ "date": "2015-01-02" } 
PUT datetest/_doc/3
{ "date": "2015-01-03" } 

POST /datetest/_search?size=0
{
  "aggs": {
    "prices": {
      "histogram": {
        "field": "date",
        "interval": 86400000.0,
        "offset": 0
      }
    }
  }
}

"perday" : {
  "buckets" : [
    {
      "key_as_string" : "2015-01-01 00:00:00",
      "key" : 1.4200704E12,
      "doc_count" : 1
    },
    {
      "key_as_string" : "2015-01-02 00:00:00",
      "key" : 1.4201568E12,
      "doc_count" : 1
    },
    {
      "key_as_string" : "2015-01-03 00:00:00",
      "key" : 1.4202432E12,
      "doc_count" : 1
    },
    {
      "key_as_string" : "2015-01-04 00:00:00",
      "key" : 1.4203296E12,
      "doc_count" : 1
    }
  ]
}

```

**Comment by fulmicoton** [comment]
That's not a pretty API :) >.<

**Comment by fulmicoton** [comment]
Can you just use rfc3339?

We have something nicer in Quickwit... Where we make it possible for users to define an output format.

**Comment by PSeitz** [comment]
> Can you just use rfc3339?

Yes, I added that to the PR: https://github.com/quickwit-oss/tantivy/pull/1693

> 
> We have something nicer in Quickwit... Where we make it possible for users to define an output format.

In quickwit we could do a post-processing and overwrite `key_as_string`

**Comment by PSeitz** [comment]
> That's not a pretty API :) >.<

Ugly enough to not be documented in the elastic search docs :)


Example for range query on date fields. 
Ranges can optionally be provided as strings. For that we would also need different formats to parse them. I tend to solution 2: Provide the formats in the aggregation request. 

```rust
pub struct RangeAggregation {
    /// The field to aggregate on.
    pub field: String,
    /// Date formats to try when field is a date type
    date_format: Option<String>
    ...,
}
```

```json

POST /datetest/_search?size=0
{
  "aggs": {
    "price_ranges": {
      "range": {
        "field": "date",
        "ranges": [
          { "to": "2015-01-01 00:00:00" },
          { "from": "2015-01-01 00:00:00", "to": "2015-01-02 00:00:00" },
          { "from": "2015-01-02 00:00:00" }
        ]
      }
    }
  }
}


"price_ranges" : {
  "buckets" : [
    {
      "key" : "*-2015-01-01 00:00:00",
      "to" : 1.4200704E12,
      "to_as_string" : "2015-01-01 00:00:00",
      "doc_count" : 0
    },
    {
      "key" : "2015-01-01 00:00:00-2015-01-02 00:00:00",
      "from" : 1.4200704E12,
      "from_as_string" : "2015-01-01 00:00:00",
      "to" : 1.4201568E12,
      "to_as_string" : "2015-01-02 00:00:00",
      "doc_count" : 1
    },
    {
      "key" : "2015-01-02 00:00:00-*",
      "from" : 1.4201568E12,
      "from_as_string" : "2015-01-02 00:00:00",
      "doc_count" : 3
    }
  ]
}


```
