### ISSUE TITLE
Bytes FastField and FilterCollector

### ISSUE THREAD

**Issue by danielhstahl** [quickwit-inc/tantivy#1333]
**Describe the bug**
The docs state [here](https://docs.rs/tantivy/latest/tantivy/fastfield/index.html) that bytes are supported as a FastField.  Indeed, this code works: `schema_builder.add_bytes_field("file_path", INDEXED | FAST);`

The docs [here](https://docs.rs/tantivy/latest/tantivy/collector/struct.FilterCollector.html) describe using a FilterCollector on FastFields.  However, when I try to implement the FilterCollector for a bytes FastField I cannot get the `predicate` to accept a parameter of type `[u8]` or `Vec<u8>`: "the trait bound `Vec<u8>: FastValue` is not satisfied
the trait `FastValue` is not implemented for `Vec<u8>`"

**Which version of tantivy are you using?**
0.17.0

**Comment by fulmicoton** [comment]
Ah yes... We should probably fix the documentation.
You cannot use the FilterCollector with a bytes field.

Do you need help working around this?
You could implement your own custom FilterCollector, it is quite straightforward.

**Comment by danielhstahl** [comment]
I'm looking into doing a custom filter.  This seems to be where the filtering occurs: https://github.com/quickwit-oss/tantivy/blob/main/src/collector/filter_collector_wrapper.rs#L178-L180. How would I get around the FastField constraint since it seems like bytes are not implemented for FastFields?

**Comment by fulmicoton** [comment]
I'm not sure I understand the question. Here is an example usage of a bytes fastfield reader. https://github.com/quickwit-oss/tantivy/blob/6656a70d1b1d88600fee993c371fdece0cf4caa9/src/fastfield/bytes/mod.rs#L15-L38

**Comment by danielhstahl** [comment]
Ok, I got it.  

The use of the static lifetime seems to be an issue though...I am using a filter based on values that I'm passing in to Tantivy which obviously aren't static so I'm getting a compiler error.

```
fn filter_results(files_lookup: &HashMap<&[u8], &std::string::String>, key: &[u8]) -> bool {
    match files_lookup.get(key) {
        Some(_result) => true,
        None => false,
    }
}
//in another function
//`search_input.search_files` does not live long enough borrowed value does not live long enough
let files_lookup: HashMap<_, _> = search_input
        .search_files
        .iter()
        .map(|v| (v.as_bytes(), v))
        .collect(); //hashmap for O(1) lookups
let filter_files_collector =
        FilterCollectorBytes::new(file_path_field, &|key| filter_results(&files_lookup, key), TopDocs::with_limit(limit));



```

**Comment by fulmicoton** [comment]
lack some context, but here are a couple of pointers.

I suspect you should just move the map into `FilterCollectorBytes`. If the map never changes and is large, you can avoid the map cloning by wrapping it into an Arc or reuse the collector object itself.
If it is small, you could just move it into the closure.

I'll close this issue now as this is reaching the realm of general rust questions.

**Comment by oppiliappan** [comment]
I am currently looking to implement a custom `FilteredCollector`, but from what I understand, it is not possible filter upon fields that are not fast. 

@fulmicoton could you throw me a bone and help me implement a custom `FilteredCollector` that runs a filter on a, say, `&str` field? My end goal here is to retrieve a top-K set of documents that obey a certain regex filter, would this be the right approach?

**Comment by fulmicoton** [comment]
The first obvious solution would be to use a `RegexQuery` and not use a collector.

Another solution would be to use a string fast field.
