### ISSUE TITLE
Avoid slicing a string in DocParsingError

### ISSUE THREAD

**Issue by fmassot** [quickwit-inc/tantivy#1339]
Done here: https://github.com/quickwit-oss/tantivy/blob/main/src/schema/schema.rs#L402-L412

Better with `invalid_json.chars().take(20)` :)

**Comment by waywardmonkeys** [comment]
The version for those line numbers would be https://github.com/quickwit-oss/tantivy/blob/bb5254de124f63cd58427db7d5a8c2d404feda69/src/schema/schema.rs#L402-L412
