### ISSUE TITLE
Got "Query is invalid. SyntaxError" when build json examples.

### ISSUE THREAD

**Issue by saukymo** [quickwit-inc/tantivy#1348]
**Describe the bug**
- What did you do?
Build json examples: https://github.com/quickwit-oss/tantivy/blob/main/examples/json_field.rs
- What happened?
Got `Error: InvalidArgument("Query is invalid. SyntaxError")`
- What was expected?
Parse the query correctly and get result.

**Which version of tantivy are you using?**
If "master",  ideally give the specific sha1 revision.

tantivy v0.17.0

**To Reproduce**

1. `cargo new tantivy-examples`
2. `cd tantivy-examples`
3. add tantivy = "0.17" to cargo.toml
4. replace main.rs with https://github.com/quickwit-oss/tantivy/blob/main/examples/json_field.rs
5. cargo run
6. Got Error: InvalidArgument("Query is invalid. SyntaxError")

If your bug is deterministic, can you give a minimal reproducing code?
Some bugs are not deterministic. Can you describe with precision in which context it happened?
If this is possible, can you share your code?

**Comment by saukymo** [comment]
Tested with master branch: Compiling tantivy v0.17.0 (https://github.com/quickwit-oss/tantivy#ae83fc82) has no issue.

**Comment by fulmicoton** [comment]
Confirmed.

**Comment by kamibo** [comment]
It looks like "query-grammar" crate has not been bumped when releasing the last version (0.17).

**Comment by saroh** [comment]
It should be fixed on `main` following https://github.com/quickwit-oss/tantivy/pull/1373 , wasn't aware of there was an issue open.

**Comment by fulmicoton** [comment]
Awesome thank you @saroh

**Comment by waywardmonkeys** [comment]
@fulmicoton This can be closed, it works on `master` (I can build and run that example without an assertion / error.)
