### ISSUE TITLE
What dataset is your benchmark using?

### ISSUE THREAD

**Issue by eeeebbbbrrrr** [quickwit-inc/tantivy#1351]
Random question, regarding https://tantivy-search.github.io/bench/ ... what dataset is it using and is it publicly available?

Thanks!

eric

**Comment by fmassot** [comment]
Hi Eric! Here is the repository: https://github.com/quickwit-oss/search-benchmark-game

In the readme, you will find the right info:
> Different search engine implementation are benched over different real-life tests. The corpus used is the English wikipedia. Stemming is disabled. Queries have been derived from the [AOL query dataset](https://en.wikipedia.org/wiki/AOL_search_data_leak) (but do not contain any personal information).

And of course, you can run the benchmark yourself and add new search engine (we would love too :))!

**Comment by eeeebbbbrrrr** [comment]
Thanks a bunch!
