### ISSUE TITLE
How can I get a snapshot of tantivy

### ISSUE THREAD

**Issue by flike** [quickwit-inc/tantivy#1377]
I want to send the total data of tantivy, I think i need a snapshot, but I can't find a method of get snapshot in tantivy.

**Comment by PSeitz** [comment]
You can just copy the whole directory with the segments data, meta.json etc.

**Comment by flike** [comment]
should I close the index writer before copy directory ？

**Comment by PSeitz** [comment]
I think it should be fine without, since any potential commit should be atomic.
When there is a serialization running, there maybe files which are not yet active.

**Comment by flike** [comment]
ok，thank you

**Comment by fulmicoton** [comment]
@flike 

- if you added documents, first, commit
- wait for merge threads (that's the name of method)
- make a copy of the entire directory.
- then resume indexing.
