### ISSUE TITLE
Occasional subtract-with-overflow panic in u64 fastfield access

### ISSUE THREAD

**Issue by mikkeldenker** [quickwit-inc/tantivy#1440]
**Describe the bug**
Sometimes an `attempt to subtract with overflow` panic occurs when reading an u64-fastfield. The panic specifically occurs on [this line](https://github.com/quickwit-oss/tantivy/blob/main/fastfield_codecs/src/multilinearinterpol.rs#L166) where `interpolation.positive_val_offset` would have an unexpectedly large value.
The values observed are:
```
calculated_value = 1432057903
diff = 184630655
interpolation.positive_val_offset = 18446744073709551557
```

As suggested by @PSeitz on discord the issue probably comes from a wrongfull cast to `u64` in the `get_calculated_value` function which causes `interpolation.positive_val_offset` to be set to a value very close to `u64::MAX` when serialized (from [here](https://github.com/quickwit-oss/tantivy/blob/main/fastfield_codecs/src/multilinearinterpol.rs#L240-L256)).

**Which version of tantivy are you using?**
`tantivy = "0.18.0"`

**To Reproduce**
I haven't been able to consistently reproduce the issue.  @PSeitz suggested a solution which might have solved the issue, but since I wasn't able to consistently reproduce the issue before the change, this is very hard to tell. I will open a pull request with the proposed solution

**Comment by PSeitz** [comment]
I could reproduce the bug in https://github.com/quickwit-oss/tantivy/pull/1432 test_gcd_date test. It's fixed now on the main branch.
