### ISSUE TITLE
Terms from tantivy index by doc address

### ISSUE THREAD

**Issue by VsevolodZakharov** [quickwit-inc/tantivy#1520]
Is it possible to get a list of indexed terms from tantivy index for a given document? i.e for the case when there is no stored fields in the schema.

**Comment by PSeitz** [comment]
Currently there is no index for that in tantivy. We use an inverted index ([postings list](https://docs.rs/tantivy/latest/tantivy/postings/index.html)) for search in the other direction term_id -> list of doc ids.

What do you need it for?

**Comment by VsevolodZakharov** [comment]
For debugging, it would be convenient to check indexed terms for a given document id (address) - some of expected search results are missing now to me - I'm trying to figure out why.

**Comment by adamreichold** [comment]
Depending on how large your index is this might be infeasible, but can iterate all the terms and their associated documents and filter out those terms which match the document you are interested in. The runtime is obviously horrible, but it might suffice for debugging purposes?

**Comment by PSeitz** [comment]
You can try to pass the text to the tokenizer you use (`TEXT` => https://docs.rs/tantivy/latest/tantivy/tokenizer/struct.TextAnalyzer.html) and check the output. This is what is stored in the term dicitonary and is searchable. Or you can provide a minimal example here. Document, config, and a search query that doesn't return the document.

**Comment by VsevolodZakharov** [comment]
The index is relatively large ~5G. I see - there is no easy way to do that. Thanks guys!
