### ISSUE TITLE
Why doesn't DateTime implement FastValue?

### ISSUE THREAD

**Issue by Kijewski** [quickwit-inc/tantivy#1523]
I'm probably missing some simple fact, but should't [`DateTime`](https://docs.rs/tantivy/0.18.0/tantivy/struct.DateTime.html) implement [`FastValue`](https://docs.rs/tantivy/0.18.0/tantivy/fastfield/trait.FastValue.html)? According to the documentation and the API, DateTime is more or less simply a wrapper around i64. Their binary representation should be the same, and `i64` does implement `FastValue`.

**Comment by fulmicoton** [comment]
@PSeitz can you have a look?

**Comment by PSeitz** [comment]
This is implemented by now
