### ISSUE TITLE
Investigate Multivalue Fastfield indexing regression 

### ISSUE THREAD

**Issue by PSeitz** [quickwit-inc/tantivy#1542]
Previously we passed typed iterators into the construction, which were used for serializing the data. The random access `Column` trait was only used for estimation.

Now we pass `Column` for both, which only has `Box<Iterator>`. The `get_val` alternative is slower and is used currently in the line train method. 

Strongly typed iterators on the type are currently impossible, due limitations on `impl Trait` (maybe resolved in next stable rust with GAT, or more [return_position_impl_trait_in_trait](https://github.com/rust-lang/rust/labels/F-return_position_impl_trait_in_trait), Update: That's the correct tracking issue https://github.com/rust-lang/rust/issues/63063)

**Comment by PSeitz** [comment]
I think we should have a different API for fastfield creation than for regular fastfield access.

On creation we want:
- Some samples for estimation
- The new data in order (an iterator or similar should be fine)
- min/max/num values

Currently we use the `Column` trait here and the implementors are wrappers in merge and initial segment creation.

On regular search/aggregation we want:
- Incremental(?) random access
- maybe some stats

We use the `Column` trait and the implementors are the fastfield codecs.

I'd therefore propose to split the traits. The use cases are different and there is no overlap on the types. It's nice to have one trait, but it causes troubles due to different API requirements.

**Comment by fulmicoton** [comment]
I think you mean to put that last message in  https://github.com/quickwit-oss/tantivy/issues/1540

**Comment by PSeitz** [comment]
Related
https://github.com/quickwit-oss/tantivy/pull/1551
https://github.com/quickwit-oss/tantivy/pull/1549

**Comment by PSeitz** [comment]
I think this may be resolved with columnar
