### ISSUE TITLE
Nullhandling for mostly dense fastfields 

### ISSUE THREAD

**Issue by PSeitz** [quickwit-inc/tantivy#1575]
# Problem Outline
How should we store null values in fast fields for mostly dense data (most of the data is not null). Currently it's unclear where the switch between sparse and dense codecs is, but more than 50% are non-null can probably be considered dense. (it's 6,25% in Lucene)

There are two possibilities.

### Option1: Codecs choose a sentinel value
Codecs choose a sentinel value and encode null values via this value. When retrieving a values via `get_val`, the codec will convert the sentinel value to `None`.

### Option2: Dedicated index for translation

We use a regular codec to store the non-null dense data one after the other, and have a companion
index to be able to lookups.

Let's `idx` the index on our `OptionColumn`, and `idx'` the index in the list of non_null_values.
We have `idx' <= idx`. 

Codecs never store null. We keep an additional index to translate `idx => idx'`.

The format would consist of blocks of 64 documents. Each block has a 64 bits, one for each document + the original idx offset as u32. That's 1.5 bit per element. We can make larger blocks to trade performance for slightly higher compression. With increasingly larger blocks we would converge to 1 bit per element.

```rust
struct SuperbeDenseIndex{
    // the bitmap representing the presence of values for idx in [64*i..64*(i+1))
    blocks: Vec<u64>,
    // the lowest idx' associated to an idx >= `64 * i`
    offsets: Vec<u32>,
}
```

#### Operations

We have a list of required operations on the index.
- Existence Check (This should be fast, for sparse and dense)
- Translate idx => idx' (This needs to be very fast for dense, since most values do exist, so we may need to translate many values)
- Translate idx' => idx (e.g. retrieve docs for given value range idx' => idx)

# Comparison

### Performance

The dedicated index is optimized for speed, but it still causes some overhead.
The sentinel value option with bitpack codec is around 4x faster on idx => idx' operations (https://github.com/quickwit-oss/tantivy/pull/1562).
On slower codecs the ratio will be lower.

### Compression

It's 1,5 Bit per element for Option2. Given an average of 15bits per element, the cost will break even after less than 90% density in comparison to sentinel value. The index should compress better in most cases.
The size of the Option2 index would be the same as the values with 10% density and 15 bits per element. 

### Code Complexity

Option2 is clearly better, it's a generic solution for all codecs.

# Considerations

RoaringBitmap is not very well suited for the listed Operations. The translation is too slow without an additional index.

### API
Sometimes there are no null values. Should we express that in the API?

The codecs will never return `Option` with the separate dense/sparse index, that should be expressed in the API.

### Generalization
Unsure about the exact performance implications, but `idx => &[codec_idx]` translation could be considered a generalization for multi-values and existence.

If the API usage would look like this, it may be still fast enough.
```
get_vals(&[Docids]) => &[(Docid, T)]
```

### Lucene
How does Lucene do it: https://lucene.apache.org/core/9_3_0/core/org/apache/lucene/codecs/lucene90/Lucene90DocValuesFormat.html

Blocks of size 65535 (`u16::MAX`). Each block can be `sparse`, `dense` or `all`.

- For 65535 documents in a block, `all` will be chosen.

- Between 4096 and 65534 documents in a block, `dense` will be chosen.
`dense` uses blocks of 512 with bitmaps inside + an additional offset index (rank). That's around 1 bit per element.

- Less than 4096, sparse will be chosen.
`sparse` uses an u16 array of the docids (other half of the u16 is defined by the block)

### Merging Dense and Sparse codecs
The 65K block solution allows to use one index for sparse and dense, but there will be some performance overhead for the additional lookup compared to Option2.

### Dense for Sparse Computation
If we use dense for sparse: 8 million docs in a segment, and only 1 value is set.
The size would be 1,5 bit * 8 mio ~= 1,5MB for the index. 

The advantage of that is that it will be always very fast (existence check).

# Conclusion

Having a dense index for null handling seems to be the right approach.

**Comment by fulmicoton** [comment]
The lucene approach is very close to roaring bitmaps ideas.

I assume the benefit is that it avoid having to pick a single regime for the entire column:
The column can be very dense in some parts and very sparse in some parts.

I like your solution though. Do you have a plan for the sparse solution?
Can you also open a ticket to design what the traits should look like?

I tend to like the idea of having a 

```
pub trait OptionalColumn<T> {
   /// close to Column<Option<T>>
   /// but a bit different due to min and max, and also

   fn or(&self, default_val: T) -> Arc<dyn Column<T>>;

   /// and maybe even
   fn docset_with_value(&self) -> Box<dyn DocSet>;
}
```
