### ISSUE TITLE
Add examples testing to CI checks to prevent outdated examples

### ISSUE THREAD

**Issue by ChillFish8** [quickwit-inc/tantivy#1600]
Currently, we use nextest to perform the unit testing within tantivy, which is excellent however, we have lost the integrated example testing that `cargo test` gives us to make sure examples are up to date with any changes. 

The solution to this would be to add another CI check step which explicitly runs nextest with the examples directory being the target.

**Comment by adamreichold** [comment]
I just had a look into this, and this does not seem to be the case:

`cargo test` does not run the examples, it just compiles them (and thereby would flag API churn and such but not incorrect usage).

`cargo nextest run` basically starts out by running `cargo test --no-run --message-format json-render-diagnostics` and will thereby also fail on compile time errors in the examples.

**Comment by adamreichold** [comment]
Due to the above, I think this can be closed as completed.

**Comment by ChillFish8** [comment]
I agree, having re-read through all the docs this looks like the compiling will do what we need.
