### ISSUE TITLE
How to merge the index segments into one segment in a reliable way?

### ISSUE THREAD

**Issue by jobergum** [quickwit-inc/tantivy#1618]
I want to index a bunch of data and merge all segments into a single segment, which will be used in a different serving path. I'm uncertain about how this can be achieved as I'm struggling with my current approach. After I call commit on the index writer there, seem to be still merges going in the background, so when I initiate a merge, it seems to clash with existing jobs.  

```rust 
  
   let mut index_writer = index.writer(512_000_000)
   //add lots of documents
   index_writer.commit();
   //Want to merge into one segment
   let segments = index.searchable_segment_ids().expect("failed to get segments");
   println!("Merging segments {:?}", segments);

   let segment = block_on(index_writer.merge(&segments));
   match segment {
        Ok(segment) => {
            println!("Merged segment meta {:?}", segment);
        }
        Err(err) => {
            println!("Got error during merge {:?}", err);
        }
    }
    block_on(index_writer.garbage_collect_files())?;
```

In many runs, there is a panic, and the following is printed, and the index dir is left with .lock files and temp files after the program exits. 

```
Merging segments [Seg("4f675019"), Seg("266472a1"), Seg("171d9f23"), Seg("8948365e"), Seg("ecb785b8"), Seg("01bb0471"), Seg("95253e90"), Seg("3e8291c4"), Seg("7cee72b6"), Seg("cc0b2d37"), Seg("a2147508"), Seg("d8931e24"), Seg("d006a6f1"), Seg("d9cca4e0"), Seg("c78dd286"), Seg("360748eb"), Seg("080fde55"), Seg("2ca0876e"), Seg("495d467b"), Seg("3c2ce25e"), Seg("42e110d6"), Seg("43395ab3"), Seg("655e89f9"), Seg("626e3651"), Seg("047949d4"), Seg("71a30247"), Seg("d1bf421c"), Seg("9989f7bc"), Seg("b1d1fde8"), Seg("6a3d32ab"), Seg("4ab03a52"), Seg("ed17e834"), Seg("4db0edb8"), Seg("5936cebf"), Seg("45384ec0"), Seg("308402f6"), Seg("89049304"), Seg("995e8744"), Seg("16a567e0"), Seg("7c4e25ff"), Seg("341b3423"), Seg("609c2a4c"), Seg("43be6a00"), Seg("6c9eec57"), Seg("199f173d"), Seg("08eadf02"), Seg("b8141cc5")]

Got error during merge InvalidArgument("The segments that were merged could not be found in the SegmentManager. This is not necessarily a bug, and can happen after a rollback for instance.")
```

It succeeds if I add a 10-second sleep between the commit and the merge operation, so is there a different way to achieve what I want without adding that ugly sleep? 

This with tantivy 0.18

**Comment by fulmicoton** [comment]
You can call `index_writer.wait_merging_thread()` after commit.
The rather stupid thing here, is that you it consumes index writer which means you will have to recreate another writer afterwards to run your merge.

If this is a dragster race, you might want to play with the number of threads of the indexing index_writer.
More threads means faster throughput, but also smaller segments created.

**Comment by fulmicoton** [comment]
The search benchmark game does this 
https://github.com/quickwit-oss/search-benchmark-game/blob/master/engines/tantivy-0.16/src/bin/build_index.rs

**Comment by jobergum** [comment]
Thanks, @fulmicoton, that was quick! I'll experiment with the number of indexing threads. The indexing throughput is plenty already though. 

That code for batch indexing is much easier to read than the [examples ](https://github.com/quickwit-oss/tantivy/tree/main/examples). I think that most would have separate code paths for indexing and searching so having two separate examples would be something to consider.
