### ISSUE TITLE
limit num_vals in `Column` to u32

### ISSUE THREAD

**Issue by PSeitz** [quickwit-inc/tantivy#1630]
Currently the API uses `u64` to address positions in the columnar storage. That's because multi-value fields could have more than `u32::MAX` values. I think we can set that limitation to u32, since segments that large with `num_docs * avg_val_per_doc > u32::MAX` are too large anyway

**Comment by fulmicoton** [comment]
yes... and I think we can chance the `idx` to u32 too. (I forgot if there is another ticket open for this)
