### ISSUE TITLE
AllQuery does not preserve sort order prescribed by sort_by_field

### ISSUE THREAD

**Issue by vikigenius** [quickwit-inc/tantivy#1675]
**Describe the bug**
The docs suggest that the sorting used by TopDocs is stable https://docs.rs/tantivy/latest/tantivy/collector/struct.TopDocs.html

> This collector guarantees a stable sorting in case of a tie on the document score. As such, it is suitable to implement pagination.

The docs for [IndexSettings::sort_by_field](https://docs.rs/tantivy/latest/tantivy/struct.IndexSettings.html#structfield.sort_by_field) indicate that we can use it to pre sort the documents in a given order.

The docs also suggest that AllQuery or the `*` query assigns a score of 1.0 to all documents.

But I notice that it does not preserve the original sort order.

**Which version of tantivy are you using?**: master (3edf0a272409729d5892ed5d2a85de42879b171f)

**To Reproduce**

In the below snippet I try to keep the documents sorted by `sidx` field. Now when I use AllQuery I expect my returned results to be sorted by sidx. But the example shows it is not the case.

```rust
use tantivy::collector::TopDocs;
use tantivy::query::QueryParser;
use tantivy::schema::{self, Schema};
use tantivy::{doc, Index, IndexReader, IndexSettings, IndexSortByField, Order, ReloadPolicy};
use tempfile::tempdir;

fn main() {
    let index_path = tempdir().unwrap();
    assert_eq!(index_path.path().to_owned().exists(), true);
    let mut schema_builder = Schema::builder();
    schema_builder.add_text_field("title", schema::TEXT | schema::STORED);
    schema_builder.add_u64_field("sidx", schema::FAST | schema::STORED);

    let schema = schema_builder.build();
    let settings = IndexSettings {
        sort_by_field: Some(IndexSortByField {
            field: "sidx".to_owned(),
            order: Order::Asc,
        }),
        ..Default::default()
    };
    let index = Index::builder()
        .schema(schema.clone())
        .settings(settings)
        .create_in_dir(index_path.path().to_owned())
        .unwrap();
    let mut index_writer = index.writer(50_000_000).unwrap();

    let title = schema.get_field("title").unwrap();
    let sidx = schema.get_field("sidx").unwrap();

    for idx in 0..100 {
        index_writer
            .add_document(doc!(
                title => format!("Prefix{}", idx.to_string()),
                sidx => idx as u64,
            ))
            .unwrap();
    }
    index_writer.commit().unwrap();

    let reader: IndexReader = index
        .reader_builder()
        .reload_policy(ReloadPolicy::OnCommit)
        .try_into()
        .unwrap();

    let searcher = reader.searcher();

    let query_parser = QueryParser::for_index(&index, vec![]);

    let query = query_parser.parse_query("*").unwrap();

    let top_docs = searcher.search(&query, &TopDocs::with_limit(1000)).unwrap();
    let mut count = 0;
    for (_score, doc_address) in top_docs {
        let retrieved_doc = searcher.doc(doc_address).unwrap();
        let sidx = retrieved_doc
            .get_first(schema.get_field("sidx").unwrap())
            .unwrap()
            .as_u64()
            .unwrap();
        assert_eq!(count, sidx);
        dbg!(_score, sidx); // Expected documents to be sorted by sidx
        count = count + 1;
    }
}
```

**Comment by vikigenius** [comment]
On further reading I have realized that I can get the behavior I want by using `order_by_u64_field`. But still given the docs and the claims of `stable_sorting` I would expect it to be sorted even without using `order_by_u64_field`.

**Comment by PSeitz** [comment]
The stable sorting refers to the sorting between search calls. It does not say by which property the elements are stable. The [sort_by_field](https://docs.rs/tantivy/latest/tantivy/struct.IndexSettings.html#structfield.sort_by_field) parameter sorts the documents in the index and not in the search result as of now.
