### ISSUE TITLE
order_by_u64_field and order_by_fast_field should allow sorting in ascending order

### ISSUE THREAD

**Issue by vikigenius** [quickwit-inc/tantivy#1676]
**Is your feature request related to a problem? Please describe.**
Currently the `order_by_u64_field` and `order_by_fast_field` functions sort only in descending order. This is a problem and is confusing especially considering that `sort_by_field` does take Order as an argument

**Describe the solution you'd like**
Maybe let the function take Order as an additional argument

**[Optional] describe alternatives you've considered**
The current workaround I am considering is to use i64 fields with negative numbers. But this might not be easy for all use cases.

**Comment by GregoireDucharme** [comment]
Looking for the same kind of solution.
How would you do that using `sort_by_field`, I can't manage to do it

**Comment by JPDye** [comment]
I'd be happy to take this issue on.

**Comment by PSeitz** [comment]
Fixed via https://github.com/quickwit-oss/tantivy/pull/2111
