### ISSUE TITLE
String fast field change of logic

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/tantivy#1705]
String fast field built upon the work that existed in facetting... 

Facetting requires a combination of indexing and fast field of the different subpath.
We used a custom tokenizer and work above the indexing mechanism to benefit from a common dictionary.

For regular strings however, tokenization rarely makes sense. Most of the time, we want to use the raw tokenizer (for bucket aggregation) and the default tokenizer for indexing (for search).

We should keep dictionary encoding, but avoid tokenization (keep strings as raw or have them go through the tokenizer that default to raw) and ship the dicitonary within the fast field (as a header?). Encoded with an FST.

Fast field building will also be more complex.

The Writer will be equivalent to a 

```rust
FastFieldWriter {
   doc_values: HashMap<String, Vec<UnorderedTermID>>,
   term_dictionary: HashMap<String, UnorderedTermID>,
}
```

**Comment by PSeitz** [comment]
Having a different tokenizer for the fast-field is a good idea, but I would make it configurable and not fix it to raw. There also may be scenarios, where dictionary duplication is wasteful.

**Comment by fulmicoton** [comment]
@PSeitz I think we should not care about dictionary duplication here. Configurable tokenizer is ok for me. It really don't believe in actual tokenization (as in splitting the string into tokens) but it might be useful for normalization maybe?
