### ISSUE TITLE
Is it possible to use different tokenizers on the same field?

### ISSUE THREAD

**Issue by Nickersoft** [quickwit-inc/tantivy#1708]
Hey folks,

I'll preface this by saying that not only am I new to Tantivy, but I'm a bit new to Rust in general and am still learning the ropes lol. I'm currently using Tantivy to index a series of documents that all have both a `text` field and a `language` field. Tantivy naturally is fine indexing all Latin-based languages, however, for documents where the `language` is specified as a CJK language, I'd like to be able to use the appropriate tokenizer to index the text. 

Given the current capabilities of this library, is this possible? The only other thought I had was creating separate fields for CJK text, store the text in the correct one based on language, query all of them when running a query, then only printing the non-empty fields (which should be 1 per document). I thought about writing my own tokenizer to wrap the other tokenizers, but I would only have access to the `text` field, not the `language`, so it wouldn't make much sense anyway.

Any help here would be appreciated. It's relatively hard to find good docs about this stuff online 😅  Thanks!!

**Comment by PSeitz** [comment]
Tokenizers are currently configured and initialized per field, there's no dynamic tokenizer mechanism. 

You could have a tokenizer with a language detection or have seperate fields.
