### ISSUE TITLE
`delete_term` is not deleting documents

### ISSUE THREAD

**Issue by emmyoh** [quickwit-inc/tantivy#1741]
**Describe the bug**
- What did you do?
I created several documents and saved the index to a folder.\
I then restarted my program, and, this time, attempted to use `delete_term` to delete the document.\
I then restarted my program, and, this time, ran a query which showed the document was still there.\
Each time the program restarts, it reads the index from the filesystem again.
- What happened?
The new query shows the document which should've been deleted.
- What was expected?
That the new query would not show the document which should've been deleted.

**Which version of tantivy are you using?**
`0.19.0` with features `mmap` and `lz4-compression`

**To Reproduce**

If your bug is deterministic, can you give a minimal reproducing code?
Some bugs are not deterministic. Can you describe with precision in which context it happened?
If this is possible, can you share your code?

Here's a link to the code file in which this bug appears: https://github.com/Dirout/vaultist/blob/master/src/main.rs
Essentially, I'm building a secret manager (like an unstructured password manager of sorts for storing any type of secret string). Some of the functionality includes: adding secrets into a vault, reading secrets from a vault, and deleting secrets from a vault.\
For the purposes of either reading or deleting secrets, I'm using Tantivy to store records of the secrets so the user can search and select which secret they'd like to either read or delete.

Here is how I'm creating the index when the vault is first made:
```rust
let mut schema_builder = Schema::builder();
let _name = schema_builder.add_text_field("title", TEXT | STORED);
let _id = schema_builder.add_text_field("id", TEXT | STORED);
let _last_modified = schema_builder.add_text_field("last_modified", TEXT | STORED);
let schema = schema_builder.build();
let index = Index::open_or_create(MmapDirectory::open(path_buf).unwrap(), schema).unwrap();
let mut index_writer = index.writer(100_000_000).unwrap();
index_writer.commit().unwrap();
```

Here is how I'm adding documents to the index:
```rust
let index = Index::open(MmapDirectory::open(path_buf).unwrap()).unwrap();
let schema = index.schema();
let name = schema.get_field("title").unwrap();
let id = schema.get_field("id").unwrap();
let last_modified = schema.get_field("last_modified").unwrap();
let mut index_writer = index.writer(100_000_000).unwrap();
index_writer
	.add_document(doc!(
		name => new_entry.clone().name,
		id => new_entry.id.to_string(),
		last_modified => new_entry.last_modified.to_rfc2822(),
	))
	.unwrap();
index_writer.commit().unwrap();
```

Here is how I'm reading documents from the index:
```rust
let index = Index::open(MmapDirectory::open(path_buf.clone()).unwrap()).unwrap();
let schema = index.schema();
let name = schema.get_field("title").unwrap();
let id = schema.get_field("id").unwrap();
let last_modified = schema.get_field("last_modified").unwrap();
let reader = index.reader().unwrap();
let searcher = reader.searcher();
let query_parser = QueryParser::for_index(&index, vec![name, id, last_modified]);

let search_query: String = Input::new()
	.with_prompt("❓ Search for the secret you're trying to view")
	.allow_empty(false)
	.interact_text_on(&Term::buffered_stdout())
	.unwrap();
let query = query_parser.parse_query(&search_query).unwrap();
let results: Vec<(Score, DocAddress)> = searcher
	.search(&query, &TopDocs::with_limit(deserialised_vault.items.len()))
	.unwrap();
```

Here is how I'm deleting documents from the index:
```rust
let index = Index::open(MmapDirectory::open(path_buf.clone()).unwrap()).unwrap();
let schema = index.schema();
let name = schema.get_field("title").unwrap();
let id = schema.get_field("id").unwrap();
let last_modified = schema.get_field("last_modified").unwrap();
let reader = index.reader().unwrap();
let searcher = reader.searcher();
let query_parser = QueryParser::for_index(&index, vec![name, id, last_modified]);

let search_query: String = Input::new()
	.with_prompt("❓ Search for the secret you're trying to remove")
	.allow_empty(false)
	.interact_text_on(&Term::buffered_stdout())
	.unwrap();
let query = query_parser.parse_query(&search_query).unwrap();
let results: Vec<(Score, DocAddress)> = searcher
	.search(&query, &TopDocs::with_limit(deserialised_vault.items.len()))
	.unwrap();
	
// Omitted code to select the document … 

let secret_id_term =
	tantivy::schema::Term::from_field_text(id, &selected_item.clone().0.id.to_string());
let mut index_writer = index.writer(100_000_000).unwrap();
index_writer.delete_term(secret_id_term);
index_writer.commit().unwrap();
reader.reload().unwrap();
```

When I run my program and have it create a vault, the index is apparently created correctly.\
When I run my program and have it add a secret, I encounter no issues. When I run my program to have it read a secret, the documents I've added show up.\
However, when I run my program and have it delete a secret, I do encounter an issue. When I run my program to have it read a secret, the documents that should've been deleted still show up.

I read #835, which sounds very similar, but could not resolve my issue.\
I read the example on deleting & updating documents (https://github.com/quickwit-inc/tantivy/blob/main/examples/deleting_updating_documents.rs), but still could not resolve my issue.

I would greatly appreciate any assistance which you could provide. Thanks!

**Comment by fulmicoton** [comment]
Before digging deeper, I strongly suspect a tokenizer problem.
```
let _id = schema_builder.add_text_field("id", TEXT | STORED);
```
```
let _id = schema_builder.add_text_field("id", STRING | STORED);
```

I strongly suspect this is your problem.

**Comment by fulmicoton** [comment]
(and thank you @emmyoh for taking the time to properly fill the issue, with instructions to reproduce and everything. It is super helpful!)

**Comment by emmyoh** [comment]
@fulmicoton That was it! Thank you so much for your help! Merry Christmas.
