### ISSUE TITLE
How to impl a custom store?

### ISSUE THREAD

**Issue by gembin** [quickwit-inc/tantivy#1748]
I'm new to tantivy, per my understanding, currently `StoreWriter` will store the docs in `.store` file.  Seems there is no store trait defined, how to impl a custom store, e.g. store the docs in a key/value store?

**Comment by PSeitz** [comment]
That's not possible currently. What's your use case?

**Comment by gembin** [comment]
I want every doc fully stored, so I dont need to query database using doc_id, and it's easy for the client to query data if we have a database as a store like tikv or mongodb etc., and it will also decouple the index storage from data storage.

**Comment by PSeitz** [comment]
You can fully store the documents in tantivy, so you don't need to query a database using doc_id. doc_id or `DocAddress` is something that's internal to tantivy and should not be used external. It's possible to compress with zstd in the docstore for better compression.

**Comment by gembin** [comment]
Thanks! Normally, how much data it can store without performance downgrade?

**Comment by fulmicoton** [comment]
You could use a fast field or a stored field to store a primary id from an external DB.

**Comment by PSeitz** [comment]
> Thanks! Normally, how much data it can store without performance downgrade?

Performance downgrade on indexing? It depends on your doc store settings (blocksize, compression algorithm, compression level). We use a separate thread to compress the doc store, so you may not notice any difference until doc store compression gets slower than regular search indexing.

Search performance is not really impacted by this.

**Comment by gembin** [comment]
Thanks, very helpful!
