### ISSUE TITLE
encode dictionary type (fst, sstable)

### ISSUE THREAD

**Issue by PSeitz** [quickwit-inc/tantivy#1827]
the dictionary is currently controlled by a feature flag to be an fst or sstable.

To make the index forward compatible we should store the dictionary type in the metadata

**Comment by trinity-1686a** [comment]
#1943 adds a footer containing the dictionary type and its version, and implement its usage for sstables. The fst part isn't implemented yet, nor is a test that read one kind of dictionary with the other reader
