### ISSUE TITLE
Counts for JSON fields

### ISSUE THREAD

**Issue by joepio** [quickwit-inc/tantivy#1832]
Hi there! I'm using Tantivy to index JSON data with an unknown schema. I'd like to get counts for certain property-value combinations. For example, a user searches for `sweater`, and I'd like to render how many `color: red` resources match that query ([more info about my use case](https://github.com/atomicdata-dev/atomic-data-rust/issues/569)).

However, I can't set `color` as a `facet_field`, as the property is unknown to my application. So I was wondering: can I use tantivy to get counts in JSON fields? If not, could this feature be added in the future? 

Thanks for maintaining this awesome library!

**Comment by PSeitz** [comment]
Hi, fast field support for json fields and therefore support for aggregations will be coming soon in the next release

**Comment by joepio** [comment]
Amazing!

**Comment by PSeitz** [comment]
This is implemented on main branch now https://github.com/quickwit-oss/tantivy/blob/e5e50603a853fbc3dd122b0ea351ba5063c7daa8/src/aggregation/agg_tests.rs#L606
