### ISSUE TITLE
Enable ZSTD compressino for large str field dictionary in the columnar format

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/tantivy#1850]
The columnar format is now embedding a dictionary within the columnar format.
For large dictionaries, it can really be worth applying ZSTD compression.

This ticket is about tweaking the format to indicate whether compression is enabled or not (at the column level)
and compress the dictionary (or the entire column) if it makes sense.

We can use a threshold (if the dict is larger than 10KB for instance) to decide when compression should kick in.

**Comment by trinity-1686a** [comment]
fixed by #1946
