### ISSUE TITLE
Revisit the sstable format

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/tantivy#1851]
The sstable format currently relies on serde cbor to encode its format. It was a decent shortcut at the time, but it would be great to remove this:
- to remove the dependency.
- to have a well-spec'ed format. 
- to have proper versioning in the format 
- to get something more compact... Right now a tiny dictionary can often top 100 bytes.

Ideally, it would be nice for the candidate format to help with the lookup.
We want the sstable index to be as small as possible as it is shipped into the hotcache.
A format that is 2x compact, means that we can have 2x smaller blocks, which in turn means 2x faster looker.

Maybe a 1 level sstable, or a k-level sstable pyramid could be a good solution.

**Comment by ppodolsky** [comment]
I've looked recently into leaked source codes of Yandex and found there something like:
- 0-level: Block-compressed delta-encoded sorted terms
- 1-level: Subindex for jumping into block
- 2-level: Index on subindex, the first letter of term

Also, there is `comptrie` used in Tomita parser, they are open sourced. Worth to check. It is trie, not fst so there is no such effective compression of suffixes but instead it implements some tricks for reordering trie layout in memory to make it more cache-aware and local.

https://github.com/yandex/tomita-parser/tree/b27ab81671057f940b383349a7d2e5e496fbbce0/src/library/comptrie

**Comment by fulmicoton** [comment]
Related #1827
