### ISSUE TITLE
How to prevent "If the indexing pipeline is full, this call may block."

### ISSUE THREAD

**Issue by saito-kosuke** [quickwit-inc/tantivy#1896]
Our source code hangs up while executing `add_document`.
Could someone tell me how to prevent the below?

If the indexing pipeline is full, this call may block.
https://docs.rs/tantivy/latest/tantivy/struct.IndexWriter.html#method.add_document

**Comment by PSeitz** [comment]
You may always hit some limits where you temporarily need to stop indexing to avoid overloading the system

Or does this hang indefinitely (which is a bug)?

**Comment by saito-kosuke** [comment]
@PSeitz 
Thank you for your answer.
This hang occurs at the same point of the source code, so the problem has been fixed after I try to commit every 100 documents.
