### ISSUE TITLE
Handle missing columns or multiple columns in aggregation

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/tantivy#1913]
After PR#1912 has landed, tantivy will be able to run aggregation over JSON fields.

This means we need to handle the case where columns are missing. 
The result shoudl be the same as if the column was not missing but "empty."

We will also need to face the possibility that we have more than one column with the same name (but different types).

As a first step we need to define a proper behavior.. The behavior is probably aggregation specific.
For instance:
- metric: pick the single numerical column (there can only be one) and ignore others.
- term aggregation: ideal implem would to the aggregation over all of the column and merge the results.

**Comment by PSeitz** [comment]
> 
> As a first step we need to define a proper behavior.. The behavior is probably aggregation specific. For instance:
> 
>     * metric: pick the single numerical column (there can only be one) and ignore others.
> 
>     * term aggregation: ideal implem would to the aggregation over all of the column and merge the results.

For the term agg and mixed types we probably would need a separate virtual column over all column indices (`ColumnIndex`) to collect the missing values. So we would aggregate over up to 3 columns (term + number + null) in a term aggregation.
