### ISSUE TITLE
sqlite fts5

### ISSUE THREAD

**Issue by tsxiaofang** [quickwit-inc/tantivy#1914]
Sqlite fts5 is faster than tantivy. Can we add this feature.

**Comment by ChillFish8** [comment]
Can I clarify *what* feature exactly? 

The FST5 module for SQLite is big and covers a lot of things (most of which tantivy already supports), or is this a request to add SQLite to the benchmark game?

**Comment by tsxiaofang** [comment]
I want to know why fts5 is faster than tantivy and where tantivy needs to be improved.

**Comment by PSeitz** [comment]
Can you share more information, where fts5 is faster?
Which queries on what dataset
