### ISSUE TITLE
perf: dynamic dispatch overhead

### ISSUE THREAD

**Issue by PSeitz** [quickwit-inc/tantivy#1922]
This flamegraph is an term query aggregation on 10mio documents selected via a "*" query. 
Only around 60% is spent in the aggregation, a large chunk seems to be calling overhead, e.g the dynamic dispatch on the callback in `for_each_docset`.

```rust 
pub(crate) fn for_each_docset<T: DocSet + ?Sized>(docset: &mut T, callback: &mut dyn FnMut(DocId)) {
    let mut doc = docset.doc();
    while doc != TERMINATED {
        callback(doc);
        doc = docset.advance();
    }
}
```

![flamegraph](https://user-images.githubusercontent.com/1109503/222384687-e1512f41-18ef-4f3f-b880-28ae034c5f44.svg)

**Comment by fulmicoton** [comment]
considering you do buffering in the aggregation layer, should we add some buffering solution in at the DocSet level maybe? can you experiment?

**Comment by PSeitz** [comment]
Yes, I think we have two options
- Buffering like in aggregations. It probably needs to be on the `Collector`, but could be combined with `DocSet`
- Remove the callback dynamic dispatch (maybe not feasible)

Buffering may have some free positive side effects on the generated code, but the (sometimes unused) score may complicate things a bit

**Comment by PSeitz** [comment]
https://github.com/quickwit-oss/tantivy/pull/1937
