### ISSUE TITLE
Phrase wit Slop Bug

### ISSUE THREAD

**Issue by inzanez** [quickwit-inc/tantivy#1934]
Hi

Am I correct that proximity search does not handle transpositions? So having indexed something like:
`"This is a big grey wolf"`

the query

`"wolf big"~3`

would not match. Right? I would have to reverse this like:

`"wolf big"~3 OR "big wolf"~3`

if I wanted something like "the word `big` occurring next to `wolf` with a word distance of **up to '3'**, no matter which way around"
...

Quick update: on small samples I do get results that work in both ways. On my larger index datasets the proximity search seems not to be exact / consistent,...not really sure why.

**Comment by inzanez** [comment]
Ok, quick update:

I built an index following the basic sample. I used a large document corpus (emails in text form). Now I also stored the file name of the email in the index, so I have the email-text and the filename itself indexed.

The email text I am looking at is as follows:
```
From    : Peter Pan [peterpan@test.com]
Sent    : 1/14/2115 2:03:52 PM
To      : Captain Hook [hook@somethingelse.com]
Subject : Re: This is for Wendy another test email some more information xxx long subject

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam

e et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no

Sent from my iPhone

> On 13 Jan 2114, at 6:11 pm, Captain Hook <chook@sdfj.com> wrote:
>
> e et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no
```
I am running the following search:
`query_parser.parse_query("\"captain wendy\"~10")?;`

And I do get **zero** results. I just searched that email in the index by its filename and retrieved the "text" portion to check if the stored text really matches the email above:
`Some(Str("From    : Peter Pan [peterpan@test.com]\r\nSent    : 1/14/2115 2:03:52 PM\r\nTo      : Captain Hook [hook@somethingelse.com]\r\nSubject : Re: This is for Wendy another test email some more information xxx long subject\r\n\r\nLorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam\r\n\r\ne et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no\r\n\r\nSent from my iPhone\r\n\r\n> On 13 Jan 2114, at 6:11 pm, Captain Hook <chook@sdfj.com> wrote:\r\n>\r\n> e et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no\r\n"))`

It does. In addition, I created a quick in-memory-index test with only this email text and the same search query, which returns a result:

```
fn test() -> Result<(), Error> {
    let mut schema_builder = Schema::builder();
    schema_builder.add_text_field("text", TEXT | STORED );
    let schema = schema_builder.build();

    let index = Index::create_in_ram(schema.clone());
    let mut index_writer = index.writer(50_000_000)?;
    let text = schema.get_field("text").unwrap();

    index_writer.add_document(doc!(text => r#"From    : Peter Pan [peterpan@test.com]
Sent    : 1/14/2115 2:03:52 PM
To      : Captain Hook [hook@somethingelse.com]
Subject : Re: This is for Wendy another test email some more information xxx long subject

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam

e et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no

Sent from my iPhone

> On 13 Jan 2114, at 6:11 pm, Captain Hook <chook@sdfj.com> wrote:
>
> e et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no
"#))?;
    index_writer.commit()?;

    let reader = index
        .reader_builder()
        .reload_policy(ReloadPolicy::OnCommit)
        .try_into()?;
    let searcher = reader.searcher();

    let query_parser = QueryParser::for_index(&index, vec![text]);
    let query = query_parser.parse_query("\"captain wendy\"~10")?;
    let top_docs = searcher.search(&query, &TopDocs::with_limit(15))?;

    for (_score, doc_address) in top_docs {
        let retrieved_doc = searcher.doc(doc_address)?;
        println!("{}", schema.to_json(&retrieved_doc));
    }

    Ok(())
}
```

What might be the reason for this? Is this a bug or is there something I missed?

**Comment by inzanez** [comment]
Anybody got a clue?...

**Comment by PSeitz** [comment]
Do you have the same tokenizer settings (`TEXT`) on both examples?
Can you give an example that doesn't work as expected?

The slop algorithm is located here, you could print some debug info for your queries: https://github.com/quickwit-oss/tantivy/blob/main/src/query/phrase_query/phrase_scorer.rs#L141

**Comment by inzanez** [comment]
@PSeitz Yes. Let me see,...I will check out the debug information tonight; I will also try and put together a sample dataset. Not sure if that will work, but potentially possible. Will get back with some more data...

**Comment by inzanez** [comment]
@PSeitz 
[proximity.zip](https://github.com/quickwit-oss/tantivy/files/10984397/proximity.zip)

The zip contains a rust project ready to run including sample data. I had to search some non-private sample data that worked, as apparently not all data has the issue. I still haven't found why some file collections do have the issue while others do not. In the two sample sets, there is always the file 'Email_00143975.txt' as a last file which should return on the search query in the code. Running the code will sometimes return a hit, sometimes not.
I run the same code on the two samples. The samples differ only in the number of files that are ingested before the actual file that should hit. It seems that the more files are ingested before that file, the scarcer the hits.

**Comment by sftse** [comment]
This is due to a race condition when the writer is multithreaded, which leads to `left` and `right` not being passed in a consistent order to `fn intersection_count_with_slop`. Unsure how to fix.

**Comment by PSeitz** [comment]
@sftse Which writer do you mean? There is not much multi-threading in tantivy

**Comment by sftse** [comment]
The `IndexWriter` is by default multithreaded. I've confirmed that the above provided example works deterministically over multiple index constructions over the same dataset, i.e always matches or does not match a given proximity query, when `fn writer_with_num_threads` is used to turn off multithreaded indexing.

**Comment by PSeitz** [comment]
The issue seems to start to appear after a certain size threshold.
More threads means more smaller segments. That's not a race condition, that's just a side effect.

Especially it never hits (but should) with a single thread.

**Comment by PSeitz** [comment]
Minimal example

```rust
use anyhow::Error;
use tantivy::collector::TopDocs;
use tantivy::query::QueryParser;
use tantivy::schema::Schema;
use tantivy::schema::STORED;
use tantivy::schema::TEXT;
use tantivy::Document;
use tantivy::Index;

fn main() -> Result<(), Error> {
    let mut schema_builder = Schema::builder();
    schema_builder.add_text_field("email_text", TEXT | STORED);
    let schema = schema_builder.build();

    let file_name = schema.get_field("file_name").unwrap();
    let email_text = schema.get_field("email_text").unwrap();

    let index = Index::create_in_ram(schema.clone());
    let mut index_writer = index.writer_with_num_threads(1, 50_000_000)?;

    let mut doc = Document::default();
    doc.add_text(email_text, "Captain");
    index_writer.add_document(doc)?;

    let mut doc = Document::default();
    doc.add_text(email_text, "Captain Subject Wendy");
    index_writer.add_document(doc)?;

    index_writer.commit()?;

    let reader = index.reader()?;
    let searcher = reader.searcher();

    let query_parser = QueryParser::for_index(&index, vec![file_name, email_text]);
    let query = query_parser.parse_query("\"captain wendy\"~10")?;

    let top_docs = searcher.search(&query, &TopDocs::with_limit(10))?;
    assert_eq!(top_docs.len(), 1);

    Ok(())
}
```

**Comment by inzanez** [comment]
> The issue seems to start to appear after a certain size threshold. More threads means more smaller segments. That's not a race condition, that's just a side effect.
> 
> Especially it never hits (but should) with a single thread.

Not really sure what you mean by "size threshold". At least I can confirm that using the same code as in the sample project above but using a different dataset (although 10x larger than the sample) the result gets returned as expected. So it cannot just be size-related on 'byte-level'. At least not the byte-size of the initial corpus. Maybe of the index, I have not checked that.

**Comment by PSeitz** [comment]
I already posted a minimal example with 2 documents that fails, there's no reason to discuss about previous guesses

**Comment by inzanez** [comment]
No, but it would certainly help if you were a bit more specific. I see your sample; but I asked what you mean with ‚size threshold‘. That would allow me to understand better. Is that determined automatically? Is it depending on what? Dataset size, thread count, a specific option that can be controlled,…?
Because that would allow me to rate and place all the tests I have done in relation to what you suggest...

**Comment by PSeitz** [comment]
The error occurs when two documents in the same segment share tokens like in the minimal example.
Obviously with bigger segments, that's more likely, which reflects the size threshold observation
