### ISSUE TITLE
Consider a JSON alternative to QueryParser strings

### ISSUE THREAD

**Issue by joepio** [quickwit-inc/tantivy#1939]
**Is your feature request related to a problem? Please describe.**
The `QueryParser` offers a very powerful language for creating custom queries. It instantly feels familiar and logical, and in some cases it might even be usable as-is in end-user contexts. Unfortunately, it can be a bit difficult to handle in the case of more complex queries, especially when [special characters need to be escaped](#1931). This is because it is a _custom serialisation format for a structured input_. Having a standardized / common serialization format like JSON eliminates these issues.  I can imagine it also makes _parsing_ the query easier since you can use something like Serde to turn the JSON into rust structs.

Some arguments in favor of adding JSON support for Query building:

- Manipulating JSON is often easier than manipulating strings
- JSON objects can be type-checked (in typescript envs, for example)
- Escaping special characters is no longer necessary
- Easier to learn for newcomers than a new query language. 

**Describe the solution you'd like**
I think adding a `Query::from_json_string` type of method would be really useful here. Alternatives like ElasticSearch and MeiliSearch offer **JSON-based query syntax**. These both work quite differently. Elasticsearch seems quite verbose and structured ([everything in JSON fields](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html)), whereas MeiliSearch takes more of a hybrid approach (inspired by Algolia, [JSON strings to represent key-value pairs, for example](https://docs.meilisearch.com/reference/api/search.html#filter)).

Possibly related: https://github.com/quickwit-oss/quickwit/issues/2501

**Comment by fulmicoton** [comment]
We will offer a JSON query DSL in quckwit in a few month.
... but contrary to meili, algolia or quickiwt, tantivy is a library

It is meant to give all of the tools for users to build whatever they want, but it should not make too many choices in their place.

You can build such a DSL in your application.
