### ISSUE TITLE
Index a document in async application

### ISSUE THREAD

**Issue by soasada** [quickwit-inc/tantivy#1974]
Hi, I don't have much experience with rust and tantivy but I'm a little bit confused.

I'm using axum as a web framework, along with async tokio. Everything is async so tantivy must be used with caution here. When I try to index a document the flow is the following:

1. POST HTTP request comes to the server. I will omit this part, but basically is calling another function called `do_index`.
2. The body is then indexed.

to do that I have the following function:

```rust
use std::sync::Arc;
use tokio::sync::RwLock;

pub async fn do_index(indexer: impl Indexer, index_writer: Arc<RwLock<IndexWriter>>) {
    let document = indexer.new_document();

    let read_lock = index_writer.read().await;
    read_lock.add_document(document).unwrap();
    drop(read_lock);

    let blocking_write = tokio::task::spawn_blocking({
        let index_writer = Arc::clone(&index_writer);

        move || {
            let mut write_lock = index_writer.blocking_write();
            write_lock.commit().unwrap();
        }
    });

    blocking_write.await.unwrap();
}
```
Shall I use the `spawn_blocking` for `commits`? also, shall I use it for `add_document`? Is there any idiomatic way of doing it?

**Comment by fmassot** [comment]
Hi @soasada

Yes, generally speaking, you should use `spawn_blocking` for any CPU tasks, and a commit is taking some CPU and can block. Refer to this [blog post](https://ryhl.io/blog/async-what-is-blocking/), which says `a good rule of thumb is no more than 10 to 100 microseconds between each .await`.

Another point: it's very inefficient to commit one document at a time, you should batch your documents whenever possible.

**Comment by fmassot** [comment]
Also, you should look at the projects using tantivy.

[Quickwit](http://github.com/quickwit-oss/quickwit) is one of them but it does not support deletion and you may want that. 

You will surely find some good ones here: https://github.com/topics/tantivy

**Comment by soasada** [comment]
hi again @fmassot, I have another question, should I use `spawn_blocking` when doing a search?
