### ISSUE TITLE
Is the benchmark setup code available somewhere?

### ISSUE THREAD

**Issue by Tony-X** [quickwit-inc/tantivy#1983]
Hi, this crate is super interesting, great work!

I am a mature user of Lucene and I want to evaluate tantivy. I would like to know more details about the benchmarks themselves. 

This is the benchmarks I was referring to https://tantivy-search.github.io/bench/

Thanks,
Tony

**Comment by Tony-X** [comment]
I searched a bit in the history and found this -- https://github.com/jason-wolfe/search-index-benchmark-game/tree/master/lucene

Looks like that repo is quite outdated and I'm sure it is not using the greatest and latest version of both Tantivy and Lucene

**Comment by fmassot** [comment]
@Tony-X I think you are looking for this repository: https://github.com/quickwit-oss/search-benchmark-game

**Comment by fulmicoton** [comment]
Jason Wolfe is the original author of the benchmark, but the official & maintained repository is https://github.com/quickwit-oss/search-benchmark-game

**Comment by Tony-X** [comment]
Perfect, thank you both @fulmicoton @fmassot 

If there is no specific reason to preventing it to be more discoverable, I'd suggest to put a link to [search-benchmark-game](https://github.com/quickwit-oss/search-benchmark-game) under the benchmarks section of the READEME. What do you think?

**Comment by Tony-X** [comment]
Created the small PR to do so https://github.com/quickwit-oss/tantivy/pull/1985

**Comment by Tony-X** [comment]
Sorry I had to create this PR to fix the typo I introduced. https://github.com/quickwit-oss/tantivy/pull/1989
