### ISSUE TITLE
Are add_document/delete_term and commit operations IO bound or CPU bound?

### ISSUE THREAD

**Issue by soasada** [quickwit-inc/tantivy#1993]
Hi, I would like to know if for a `MmapDirectory` based index the common operations of `IndexWriter`:

- add_document
- delete_term
- commit

Can block and the reason, if they are CPU intensive or IO blocking.

**Comment by PSeitz** [comment]
* add_document: cpu bound (commits are automatically triggered when the memory threshold is reached)
* commit is writing the segment to disk, both cpu bound and io bound (See `SegmentWriter::finalize`)
* delete_term is cpu bound (deletes will be written only after commits)

merges are scheduled in the background and are io bound. They are, depending on the merge policy, triggered by commits. (See `IndexMerger::write`)

They can all block. add_document if the internal queue is full, delete_term if the search is expensive.
If you mean with block, the time until they return.

**Comment by soasada** [comment]
Thanks for the info, yes I mean by blocking something between 10 and 100 microseconds. I'm trying to integrate tantivy in a web server using axum + tokio, so I have to take care about the async runtime.

At the moment, I'm scheduling a thread responsible of doing the commit every 30s (I don't need real time search) but I didn't know that add_document triggers a commit also. What is the memory threshold used?

**Comment by PSeitz** [comment]
The memory arena https://docs.rs/tantivy/latest/tantivy/struct.Index.html#method.writer_with_num_threads
You may want to check out https://github.com/quickwit-oss/quickwit, how it's solved there.

**Comment by soasada** [comment]
@PSeitz can you point me out to the module or crate where this is solved in quickwit?

**Comment by PSeitz** [comment]
The example may be too complex for your use case, since it is a distributed system. Just search for the tantivy functions, e.g. `add_document` https://github.com/quickwit-oss/quickwit/blob/main/quickwit/quickwit-indexing/src/actors/indexer.rs
