### ISSUE TITLE
Memory is not freed back after add documents and commit

### ISSUE THREAD

**Issue by soasada** [quickwit-inc/tantivy#1995]
Hi, 

I finally was able to put into production a small web server with tantivy, now I'm indexing some documents (a few thousands).

I'm deleting and adding the documents and every certain amount of time I commit. So far so good, but when I tested to index again the same documents the memory has increased and is not freed (after commit or after adding), even though the documents are the same and they suppose to be deleted and added again. 

I'm measuring the memory usage with `docker stats <container_name>` as I deployed the server in a docker container. Also with `htop` every time I index a batch is incrementing the memory usage and not returning back again.

Am I missing something? maybe I have to clear something after commit?

**Comment by fulmicoton** [comment]
Please try a better alllocator (chances are it is a problem of fragmentation) and share code to reproduce. Otherwise we cannot help you.

**Comment by soasada** [comment]
Hi @fulmicoton the code can be found here: https://github.com/soasada/tantivy_search, which allocator should I use?

**Comment by fmassot** [comment]
In quickwit, we use [jemalloc](https://github.com/quickwit-oss/quickwit/blob/b54d5e5bef9a3edddcb9a908bbb2fc30c7faaeb3/quickwit/quickwit-cli/src/jemalloc.rs#L26-L27) to avoid fragmentation.

**Comment by soasada** [comment]
@fmassot but why do I need an allocator?

**Comment by fmassot** [comment]
mmm, do you mean why do you need to change the default allocator?

**Comment by soasada** [comment]
Yes, exactly

**Comment by fmassot** [comment]
to avoid memory fragmentation :)

You can have a look at [jemalloc main page](https://jemalloc.net/) and this [blog post](https://www.svix.com/blog/heap-fragmentation-in-rust-applications/) that shows the benefits with an axum server :)

**Comment by soasada** [comment]
I tested mimalloc and jemalloc and the problem does not disappeared, soI think that we cannot blame the allocator here, something is wrong in axum/tokio/serde which is causing the heap fragmentation as I'm sending HTTP requests with hundreds of JSON objects to the rust server.

**Comment by fulmicoton** [comment]
At this point we havent ruled out an actual leak in tantivy have we?

**Comment by soasada** [comment]
I'm doing further investigation, I will let you know with my findings.

**Comment by soasada** [comment]
@fulmicoton @fmassot After some investigation I tried to test the application without tantivy, just to ensure that the other dependencies are not responsible of the heap fragmentation.

Test 1: Application with axum, serde and tokio. I tried to sent big JSON payloads to the server and the memory usage didn't increased too much, not consumed more than 3MB of memory and the increment of memory usage when receiving the HTTP request was held back to 3MB.

Test 2: Added tantivy to the application: https://github.com/soasada/tantivy_search and the problem then appears again. Before sending documents to index, the application is using 8-9MB of memory, after sending a batch of ~500 documents the memory usage went up to ~25MB, after sending again the same batch the memory goes up again to ~40MB and never goes back to ~25MB, which I think is the memory that makes sense because the total documents stored in the index is 500. If I continue doing it the memory is increasing.

**Comment by PSeitz** [comment]
@soasada Any insights from a memory profile?

**Comment by soasada** [comment]
After playing around with `heaptrack` and `DHAT` it seems like there is no problem with memory and tantivy, [I update the example project with a DHAT profile if you want to know more](https://github.com/soasada/tantivy_search/blob/master/dhat-heap.json). 

I'm new to rust, but my theory is that the OS is maintaining the memory allocated because any of the following:
1. The system allocator may keep the memory with the user's process after it was freed, it will avoid needless memory fragmentation and performance loss due to extra syscalls.
2. Various internal buffers will keep their memory capacity unless explicitly downsized (that's true of Vec, for example, and likely true for unbounded message queues in actix/axum).

It's not a leak, it's basically a cache. [Credits to this person from reddit](https://www.reddit.com/r/rust/comments/ybu6gz/comment/itipstv/?utm_source=reddit&utm_medium=web2x&context=3)
