### ISSUE TITLE
Enable str fast field based range queries.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/tantivy#2023]
This is for quickwit. Which means we at least want a StrFastFieldRange{Query/Weight}

**Comment by fulmicoton** [comment]
@PSeitz Do we have this already I forgot?

**Comment by PSeitz** [comment]
Currently only u64 fast fields are supported.

If we can map the str ranges to term ids as a preprocessing, reusing the existing u64 range queries on fast fields should be straight forward.
