### ISSUE TITLE
Date histogram should return keys in milliseconds to be compatible with ES

### ISSUE THREAD

**Issue by fmassot** [quickwit-inc/tantivy#2028]
Currently, keys are returned in nanoseconds.

I suggest returning by default milliseconds and having a parameter to be able to get keys in another unit.

Note that `key_as_string` can be customized by the `format` parameter which we don't support. By default, `key_as_string` returns the first format specified in the field. The `format` support can be tracked in another issue.

```json
"aggregations" : {
    "metrics" : {
      "buckets" : [
        {
          "key_as_string" : "1674285600000",
          "key" : 1674285600000,
          "doc_count" : 0
        }
      ]
   }
}
```

**Comment by fulmicoton** [comment]
@Pseitz can you handle this?
@fmassot any preference on the default key_as_string for the moment?

**Comment by fmassot** [comment]
the current default is good (formated like this `"key_as_string": "2014-12-31T00:00:00Z"`)
