### ISSUE TITLE
Snippets don't work for non-ascii languages

### ISSUE THREAD

**Issue by Revertron** [quickwit-inc/tantivy#2029]
I'm trying to use Lnx, that uses Tantivy. I've created an index with long texts, and I want to get snippets with search terms highlighted.
I've added snippeting code to my local copy of Lnx, following the example: https://github.com/quickwit-oss/tantivy/blob/main/src/snippet/mod.rs#L238.

But it is breaking the string in the middle of chars:
```
thread 'executor-pool-worker-0' panicked at 'byte index 24 is not a char boundary; it is inside 'н' (bytes 23..25) of `Валерий Дёмин
 Тайник Русского Севера
 Посвящается Игорю БОЕВУ, русскому офицеру`', ***\tantivy-0.19.2\src\snippet\mod.rs:83:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Rayon: detected unexpected panic; aborting
```

**Which version of tantivy are you using?**
I've updated the Tantivy in Lnx to 0.19.2 (didn't push the PR with changes to their repository yet).

**To Reproduce**

Just add some long Russian texts in some index and try to get snippets of found text.

**Comment by fmassot** [comment]
Thanks, @Revertron for the report. When I see this [line](https://github.com/quickwit-oss/tantivy/blob/main/src/snippet/mod.rs#LL169C30-L169C79) I'm indeed expecting the typical issue that you got :/

**Comment by fulmicoton** [comment]
@fmassot The line is not necessarily suspicious/ The offsets are supposed to be expressed in bytes and be correct utf-8 boundaries. The bug can be in the snippet or in the tokenizer lying about char offsets.

@Revertron which tokenizer are you using and can you send us a minimum reproducible example.
If you don't know how to craft such an exemple, can you at least send us a text a query, and let us know the tokenizer so we can help?

**Comment by Revertron** [comment]
@fulmicoton I've researched what tokenizer is used, it seems that in this case it is `SimpleUnicodeTokenizer`.
The problem is that those offsets are in chars, but after that they are used like they are in bytes.
I've fixed this problem locally, but now I have another problem - sometimes I get good snippets, and sometimes they are just random, even starting in the middle of the words. Or I get only a string in a form of `<b></b><b></b><b></b>`.

**Comment by Revertron** [comment]
Okay, I've found that `SimpleUnicodeTokenizer` (from Lnx) is scrambling the work with snippets. With some modifications it works.

But I have another question: does `SnippetGenerator` work with fuzzy search? Where can I get an example?

**Comment by PSeitz** [comment]
@Revertron Did you try to pass `FuzzyTermQuery` to `SnippetGenerator::create()`?

**Comment by fulmicoton** [comment]
closing.
