### ISSUE TITLE
Using bytes / text fast field with IndexSortByField

### ISSUE THREAD

**Issue by lennartvrg** [quickwit-inc/tantivy#2032]
I'm trying to use the IndexSortByField setting with a **byte** or **text** field which contains an [Ulid](https://github.com/ulid/spec). As far as I can tell from the docs the IndexSortByField setting should work with all fast fields. However, I face the following problems:

- When using a **bytes** field the index creation works without a problem, but when committing documents I get an `InvalidArgument("sort index by field is required to be a fast field \"id\"")` error.
- When using a **text** field the index creation fails with `InvalidArgument("Only single value fast field Cardinality supported for sorting index id")` even though the text field was created with the `raw` tokenizer which should result in a single value cardinality field.

I have created an [minimal example](https://github.com/lennartvrg/tantivy-issue-example) (tantivy v0.19.2) with which the problem can be recreated. To create the index with the **bytes** field run `cargo run bytes` and to create the index with the **text** field run `cargo run text`.

Did I misunderstand something about how IndexSortByField or fast text / byte fields work, or this some kind of bug?

**Comment by PSeitz** [comment]
Thanks for the bug report and the minimal example.
The index sort by field preceded the fast fields on text/bytes, and the docs haven't been updated to cover that.

Index sorting is currently only supported on numerical fast fields.


For text/bytes support, this code would need to be adjusted to handle `StrOrBytesColumnWriter`, to handle initial segment creation.
https://github.com/quickwit-oss/tantivy/blob/main/columnar/src/columnar/writer/mod.rs#L100

And this part to handle sort when segment merging.
https://github.com/quickwit-oss/tantivy/blob/main/src/indexer/merger.rs#L342

**Comment by lennartvrg** [comment]
Hey, thanks for the response. An alternative for me would be the native `u128` [Ulid](https://docs.rs/ulid/latest/ulid/struct.Ulid.html#) representation. At the moment tantivy only uses `u128` internally for the `IpAddr` field right? Is it possible to add `u128` as a regular numeric type? This would also be useful for the [Uuid](https://docs.rs/uuid/latest/uuid/struct.Uuid.html#method.as_u128) crate as those can also be represented as `u128`.

**Comment by PSeitz** [comment]
u128 would not be a regular numeric type, as it's based on u128 and not u64. It's possible to add, but not planned currently.

Why do you want to sort the index with Ulid?

**Comment by lennartvrg** [comment]
I am using Ulids as a primary key storing for log entries. They are a good fit as they are built from a millisecond precision timestamp (first 48 bits) and random bytes (last 80 bits) which prevents collisions. The random part is guaranteed to increase when two or more Ulids are generated in the same millisecond:
```
Ulid::new() // 01BX5ZZKBKACTAV9WEVGEMMVRY
Ulid::new() // 01BX5ZZKBKACTAV9WEVGEMMVRZ
```
This is quite nice as it ensures that the order in which the log entries are generated is maintained.

I could also use a regular `u64` nanosecond precision timestamp as a primary key but then I would have to deal with collisions myself. Furthermore, when displaying log entries in a JavaScript frontend, the regular `DateTime` type only supports millisecond precision anyways so sorting with nanosecond precision becomes inconvenient. Ulids solve that issue as their string representation is lexicographically sortable.

**Comment by PSeitz** [comment]
`DateTime` will support nanoseconds with the next release, and currently supports microseconds.

What is the purpose to sort the index with Ulid?

**Comment by lennartvrg** [comment]
For the vast majority of my queries I only want to look at a specific time frame. As an example: If I want to fetch all logs with a timestamp between `2023-01-01 0:00 UTC` and `2023-02-01 0:00 UTC`, I can simply run a `RangeQuery` with the Ulid range `[01GNNA1J000000000000000000, 01GR54BV000000000000000000)`. With a working `IndexSortByField` setting tantivy could already exclude a large number of segments which fall outside that range.

**Comment by PSeitz** [comment]
`IndexSortByField` only sorts segments, it will not help with pruning over multiple segments. You would need to implement that manually currently.
If you have a lot of logs and need pruning, you may want to have a look at [quickwit](https://github.com/quickwit-oss/quickwit).

**Comment by lennartvrg** [comment]
Ahh, thats unfortunate but I can deal with it on my side. Support for `u128` fields would still be useful in general but I can totally understand that this not a high priority thing for you. Thank you very much for the support :)
