### ISSUE TITLE
Is it possible to use PhraseQuery with a Stemmer?

### ISSUE THREAD

**Issue by Revertron** [quickwit-inc/tantivy#2049]
I'm trying to use PhraseQuery with stemming.
For example, I use this for the query:
```
let tokenizer = TextAnalyzer::from(SimpleTokenizer)
            .filter(LowerCaser)
            .filter(StopWordFilter::new(Language::English).unwrap())
            .filter(Stemmer::new(Language::English));
```
And then I use `PhraseQuery` to try to search some phrase. I expect Tantivy to search for all stemmed forms of words grouped like phrases. But I just have zero results. I think it is because `PhraseQuery` searches for _exact_ words. Am I right?

And what are the possibilities there to implement this kind of search?

**Comment by shikhar** [comment]
Are you using analyzed tokens for your `PhraseQuery`? That happens automatically when using Tantivy's query parsing functionality, if not you need to take care of it yourself.

**Comment by Revertron** [comment]
I didn't quite understand what do you mean by "analyzed tokens".
I have a query like this:
```
BooleanQuery { subqueries: [(Must, BooleanQuery { subqueries: [(Should, PhraseQuery { field: Field(3), phrase_terms: [(0, Term(type=Str, field=3, "program")), (1, Term(type=Str, field=3, "languag"))], slop: 3 }), (Should, PhraseQuery { field: Field(1), phrase_terms: [(0, Term(type=Str, field=1, "program")), (1, Term(type=Str, field=1, "languag"))], slop: 3 }), (Should, PhraseQuery { field: Field(4), phrase_terms: [(0, Term(type=Str, field=4, "program")), (1, Term(type=Str, field=4, "languag"))], slop: 3 })] })] }
```

**Comment by shikhar** [comment]
Ah sorry for deleting my comment, meant to be clearer and got distracted. It was along the lines of asking whether you are using Tantivy's [QueryParser](https://docs.rs/tantivy/latest/tantivy/query/struct.QueryParser.html) or constructing it with  `PhraseQuery::new()`. The latter requires you to take care of using the same tokenizer configured for your field for indexing time, which you can retrieve in several ways e.g. https://docs.rs/tantivy/latest/tantivy/struct.Index.html#method.tokenizer_for_field

It does look like your query contains analyzed tokens though, assuming the query was "programming language".

**Comment by adamreichold** [comment]
One thing that might be helpful: Since your query seems to be constructed using the built-in query parser or at least contain tokenized terms, you might have a mismatch between the tokenizer configuration used during indexing and searching?

(This is possibly already known to you:) Stemming works by storing the stems of the tokens instead of the original tokens. To match up, this must happen in the same manner during indexing of documents (which tokenized and the tokens stemmed) and during search (where your query is tokenized and the tokens stemmed).

So maybe you created your index without stemming, then modified your tokenizer settings for querying and now your query tries to match stemmed tokens against unstemmed tokens stored in your index? I think this could happen if the original tokenizer configuration using during indexing has the same name as the modified tokenizer configuration used during search.

**Comment by Revertron** [comment]
@shikhar, Yes, the query was "programming language", I construct it by hand, but I've created big function for that.
It is a fork of `Lnx`, based on `Tantivy`.
```

    /// Makes a query based on phrase consisting of 2+ words.
    fn make_phrase_query(
        &self,
        value: DocumentValue,
        slop: u32,
        field: FieldSelector,
    ) -> Result<Box<dyn Query>> {
        use tantivy::query::Occur;

        let query = value.as_string();
        if query.is_empty() {
            return Ok(Box::new(EmptyQuery {}));
        }

        let mut words = vec![];
        let mut tokens = self.tokenizer.token_stream(&query);

        while let Some(token) = tokens.next() {
            if self.ctx.strip_stop_words && self.stop_words.is_stop_word(&token.text) {
                continue;
            }

            if let Some(synonyms) = self.synonyms.get_synonyms(&token.text) {
                words.extend_from_slice(&synonyms);
            }

            words.push(token.text.clone());
        }

        if words.is_empty() {
            return Ok(Box::new(EmptyQuery {}));
        }

        let fields = {
            match field {
                FieldSelector::DefaultFields => self.ctx.default_search_fields.clone(),
                FieldSelector::Single(field) => {
                    vec![(self.get_searchable_field(&field)?, 1.0)]
                },
                FieldSelector::Multi(fields) => {
                    if fields.is_empty() {
                        return Err(anyhow!(
                            "At least one field must be specified, to use the default fields \
                            leave this field out of the query."
                        ));
                    }

                    let mut search_fields = Vec::with_capacity(fields.len());
                    for field in fields {
                        search_fields.push((self.get_searchable_field(&field)?, 1.0));
                    }

                    search_fields
                },
                FieldSelector::MultiWithBoost(fields) => {
                    if fields.is_empty() {
                        return Err(anyhow!(
                            "At least one field must be specified, to use the default fields \
                            leave this field out of the query."
                        ));
                    }

                    let mut search_fields = Vec::with_capacity(fields.len());
                    for (field, score) in fields {
                        search_fields.push((self.get_searchable_field(&field)?, score));
                    }

                    search_fields
                },
            }
        };

        let mut queries = vec![];
        for (field, boost) in fields {
            let mut field_terms = vec![];
            for word in words.iter() {
                let term = Term::from_field_text(field, word);
                field_terms.push(term);
            }

            let mut phrase_query = PhraseQuery::new(field_terms);
            phrase_query.set_slop(slop);
            queries.push((Occur::Should, Box::new(phrase_query) as Box<dyn Query>));
        }

        Ok(Box::new(BooleanQuery::new(queries)))
    }
```
I use `self.tokenizer` that should be the same for the whole index...

@adamreichold, This is an interesting question, I don't remember how I created the index at hand :)
But the fuzzy or normal (Term) queries are giving me results, but `PhraseQuery` is not.

**Comment by Revertron** [comment]
@adamreichold, you was right!
I've recreated the index, fed all the documents again, and now the search is giving me results!

Thanks a lot!
