### ISSUE TITLE
Wildcard queries with Slop

### ISSUE THREAD

**Issue by inzanez** [quickwit-inc/tantivy#2059]
Hi

is there a way to use wildcard matching together with slop? As far as I see wildcard matching is currently only supported using Regular expression queries. But they do not work together with slop...

**Comment by PSeitz** [comment]
That's not supported currently.
Do you mean phrase query with wildcard and slop?
E.g. PhrasePrefixQuery with slop

**Comment by inzanez** [comment]
Yes, exactly, a PhrasePrefixQuery with slop.
