### ISSUE TITLE
PhrasePrefixQuery with Slop

### ISSUE THREAD

**Issue by inzanez** [quickwit-inc/tantivy#2060]
Implementation to support phrase prefix queries (also with slop) would be very useful. I guess would be quite an undertaking, right?

**Comment by PSeitz** [comment]
Slop handles each term pair separate and intersects left with right positions. In the case with prefix we would need to load positions from multiple terms into right_positions.

```rust
intersection_count_with_slop(
    &mut self.left_positions,
    &self.right_positions[..],
    self.slop,
    true,
);
```

**Comment by PSeitz** [comment]
This is supported now via `RegexPhraseQuery`, which also supports slop https://github.com/quickwit-oss/tantivy/pull/2516

On a side note regex phrase + slop doesn't seem to be supported in Lucene
