### ISSUE TITLE
language bindings supported

### ISSUE THREAD

**Issue by patelprateek** [quickwit-inc/tantivy#2113]
I am trying to use tantivy as an embedded index , replacing lucene . 
I am curious if there are java , cpp and python bindings that tanitvy supports ? Curios to know how are other users buulding services around it using different lnguages.

thanks

**Comment by adamreichold** [comment]
There are Python bindings using PyO3 here: https://github.com/quickwit-oss/tantivy-py

For C++. it would probably be best to interface with Tantivy using Rust and integrate a small project-specific Rust library using somthing like [cxx.rs](https://cxx.rs/).

**Comment by fulmicoton** [comment]
The only "official" one is tantivy-py. If you search on github, I think there are (unmaintained) bindings for C, ruby, javascript, elixir.
