### ISSUE TITLE
How can I count all documents indexed?

### ISSUE THREAD

**Issue by soasada** [quickwit-inc/tantivy#2115]
Hi, I would like to know how many documents are indexed in total in my index. I know there is a `CountCollector` but it counts documents matching a query. Is there any possible way of getting all of them?

**Comment by adamreichold** [comment]
Use the [`AllQuery`](https://docs.rs/tantivy/latest/tantivy/query/struct.AllQuery.html) which is a query which returns all documents in the index as efficiently as possible. (The syntax to request this via the query parser is `*`.)
