### ISSUE TITLE
[🌍] Is tantivy support Hebrew?

### ISSUE THREAD

**Issue by barel-mishal** [quickwit-inc/tantivy#2136]
Dear Quickwit Team,

I am planning to utilize Tantivy for my side project, which involves indexing some Hebrew and English texts. I am curious to know if there are any specific caveats or considerations, I should be aware of when using a language like Hebrew?

Thank you in advance for your assistance,
Best regards,

Barel Mishal

**Comment by fulmicoton** [comment]
Hello @barel-mishal . Tantivy does not support Hebrew at the moment. 
Supporting it would mean implementing a tokenizer. It is usually done outside tantivy, by implementing the traits you will find in https://crates.io/crates/tantivy-tokenizer-api .
