### ISSUE TITLE
tantivy::DateTime overflow

### ISSUE THREAD

**Issue by shouya** [quickwit-inc/tantivy#2140]
Currently, [tantivy::DateTime](https://docs.rs/tantivy-common/0.5.0/src/tantivy_common/datetime.rs.html#43) stores a timestamp at nanosecond precision with an i64 type.

- `i64::MAX` is `9223372036854775807` which corresponds to `2262-04-12T08:47:16`.
- `i64::MIN` is `-9223372036854775808` which corresponds to `1677-09-21T08:39:43`

These bounds should be fine for contemporary events, but they may not be sufficient for broader use cases.

I noticed this issue when attempting to index documents for some sci-fi setting, where the dates of events include the near future into several hundreds years from now (e.g. year 2300). I can imagine this can also cause problems when one tries to index historical documents.

I'm wondering if there can be a way to allow the users specifying the date format with lesser precision (e.g. second) in exchange for a greater range. Thanks!

**Comment by fulmicoton** [comment]
Yes, tantivy represents datetimes with a nanoseconds precision. It makes the implementation much simpler.
(GCD detection still gives use proper compression).

> I'm wondering if there can be a way to allow the users specifying the date format with lesser precision (e.g. second) in exchange for a greater range. Thanks!

This is not possible with tantivy. I can only recommend you to encode as a unix timestamp with a i64 field.

**Comment by shouya** [comment]
True, I can see this is not a trivial thing to implement.

Another place I found interesting is the [set_precision](https://docs.rs/tantivy/latest/tantivy/schema/struct.DateOptions.html#method.set_precision) method for `DateOptions` for a date field. This option feels like it was designed to support customizable precision, isn't it?

**Comment by PSeitz** [comment]
The documentation is slightly misleading here, it's not the internal precision, but just truncating the values to the precision.

Can you check if you run into issue with a i64 field? I think one limitation is query language support

**Comment by fulmicoton** [comment]
`set_precision` truncates the precision, and it only operates on fast fields.
Its point is to make fast fields smaller.

**Comment by shouya** [comment]
> Can you check if you run into issue with a i64 field? I think one limitation is query language support

Sure. That's exactly what I'm planning to do.

The lack of query language support is a little unsatisfactory though. Perhaps we can have an extensible query syntax in the future (e.g. customizable way for converting string to term query on a per field basis). But that's a totally different issue to discuss.

>  Its point is to make fast fields smaller.

That makes sense. Thanks for explaining.
