### ISSUE TITLE
What does field `position_length` mean in Token?

### ISSUE THREAD

**Issue by zxch3n** [quickwit-inc/tantivy#2141]
Currently, the doc only describes it as "Is the length expressed in term of number of original tokens". But what does "original token" mean in this context? 

In the Chinese language, several terms may refer to an overlapped text area to avoid ambiguity. For example, `"北京大学"` can be tokenized into three tokens `["北京", "大学", "北京大学"]`. What `position_length` should be for each token?

I've seen somebody use the total token number as `position_length` in their implementation.  A better doc will be helpful.

**Comment by fulmicoton** [comment]
It is the same as position increment in Lucene. You can read about it here.

In your case, you might want to simply tokenize as `[北京, 大学]` and not bother.
If you want to go the hard way, you could have a tokenizer that tokenizes as

- 北京 position 0, positionLength 1
- 北京大学 position 0, positionLength 2
- 大学 position 1, positionLength 1

But it seems overkill to be honest.
A better use case could be synonym expansion maybe.
For instance, on the indexing only, you may want to expand your text as:

- 北京 position 0, positionLength 1
- 北大 position 0, positionLength 2 <--- coming from synonym expansion
- 大学 position 1, positionLength 1

https://blog.mikemccandless.com/2012/04/lucenes-tokenstreams-are-actually.html

**Comment by zxch3n** [comment]
Got it. Thanks.
