### ISSUE TITLE
Using Tantivy with OpenDAL instead of a Filesystem

### ISSUE THREAD

**Issue by joepio** [quickwit-inc/tantivy#2146]
**Is your feature request related to a problem? Please describe.**
I'm using Tantivy in [Atomic-Server](https://atomicserver.eu/), and I love it.

But I want to achieve two goals:

- Multi node setup
- Single-click deploys (using shuttle.rs, in a WASM runtime)

For both of these cases, I cannot use the filesystem. I'm playing with OpenDAL to achieve this. OpenDAL abstracts Key Value and Filesystem calls away, which lets me use either a normal filesystem, a KV store (like Sled or ReDB) or even a multi-node KV store like TiKV.

**Describe the solution you'd like**

Perhaps Tantivy could also depend on OpenDAL instead of the filesystem.

**[Optional] describe alternatives you've considered**

- Create my own lightweight full-text search alternative using a KV store (takes a long time, will not lead to great search experience)
- Use QuickWit for the multi-node solution (but deleting / editing stuff is difficult)

**Comment by fulmicoton** [comment]
Tantivy offers a `Directory` abstraction upon which it does all of its IO. Integrating with opendal is out of scope for tantivy, but it should be possible to build something outside of tantivy.

In fact Quickwit is precisely running tantivy from Amazon S3. I would not qualify this as easy however.

**Comment by joepio** [comment]
Thanks for sharing your thoughts, @fulmicoton !

I'll close this then.
