### ISSUE TITLE
`order_by_u64_field` made private in `0.21`

### ISSUE THREAD

**Issue by ljeub-pometry** [quickwit-inc/tantivy#2175]
**Describe the bug**
The `TopDocs::order_by_u64_field` is private in version `0.21`. 

**Which version of tantivy are you using?**
Version `0.21`

**To Reproduce**

Use `TopDocs::order_by_u64_field` outside of the tantivy crate and you get ``error[E0624]: method `order_by_u64_field` is private`` compiler error.

**Comment by PSeitz** [comment]
The method is superseded by `order_by_fast_field` https://docs.rs/tantivy/latest/tantivy/collector/struct.TopDocs.html#method.order_by_fast_field
