### ISSUE TITLE
How to achieve random presentation of search results?  Similar effect to SQL: select * from tb order by rand()

### ISSUE THREAD

**Issue by origel** [quickwit-inc/tantivy#2213]
The search set may have hundreds or thousands of data, and I want to search through certain criteria and randomly select 8 records from those that meet the criteria to return. But I haven't found a good solution yet.

**Comment by fulmicoton** [comment]
Random is ambiguous. Can you describe what you are trying to do with the search results?

Example of interpretation:
- I don't care about the random (probably not your case considering the SQL query you joined)
- I want the result to be random but in a replicable manner. Two calls should return the same result.
- I want the results to random, but I need to be able to pass a seed with the query... 
- I don't care about a perfect uniform distribution. I just need to eyeball some result sample.

**Comment by origel** [comment]
My current situation is to randomly select some sampling results without the need to pass on random number seeds.

**Comment by origel** [comment]
I want to use Tantivy's powerful search function, but for the search results, I want to present them randomly because the correlation is similar.

**Comment by fulmicoton** [comment]
What do you mean by the correlation is very similar?

**Comment by origel** [comment]
I have many SVG templates that can be matched based on user input, such as nickname length and gender, and then replaced with some content, such as replacing nicknames, and displayed to users. These templates can be recommended to users as long as they meet the conditions. But when presenting to users, try to randomly recommend different SVG templates as much as possible. So I want to randomly display 8 at a time for users, and if the user refreshes, continue to randomly display 8, which is the problem I am currently facing.

**Comment by fulmicoton** [comment]
Ok thank you!
As a work around you can use 
https://docs.rs/tantivy/latest/tantivy/collector/struct.TopDocs.html#method.custom_score

And have it return a random number.
This is not the fastest way to do things but it should work.

**Comment by origel** [comment]
> Ok thank you! As a work around you can use https://docs.rs/tantivy/latest/tantivy/collector/struct.TopDocs.html#method.custom_score
> 
> And have it return a random number. This is not the fastest way to do things but it should work.

OK, thanks!

**Comment by origel** [comment]
Success! Great thanks!
