### ISSUE TITLE
RangeQuery should take Terms or Field directly, not Strings

### ISSUE THREAD

**Issue by trinity-1686a** [quickwit-inc/tantivy#2233]
```rust
impl TermQuery {
    pub fn new(term: Term, segment_postings_options: IndexRecordOption) -> TermQuery;
}
impl RegexQuery {
    pub fn from_pattern(regex_pattern: &str, field: Field) -> crate::Result<Self>;
}
impl TermSetQuery {
    pub fn new<T: IntoIterator<Item = Term>>(terms: T) -> Self;
}


impl RangeQuery {
    pub fn new_term_bounds(
        field: String,
        value_type: Type,
        lower_bound: &Bound<Term>,
        upper_bound: &Bound<Term>,
    ) -> RangeQuery;
    pub fn new_i64(field: String, range: Range<i64>) -> RangeQuery;
    // ...
}
```

queries which interact with terms or fields take their arguments either as `Term`s (which already contain a field and a type), or when it's not possible, as a `Field`. However `RangeQuery` takes a field_name as `String` (and ignore the field set in the `Term`s, for the constructor which takes term bounds).

It should take the same kind of arguments as other queries

**Comment by PSeitz** [comment]
Fixed by https://github.com/quickwit-oss/tantivy/pull/2452
