### ISSUE TITLE
After the IndexWriter is destructed, function `garbage_collect_files` under SegmentUpdater may still continue to execute.

### ISSUE THREAD

**Issue by MochiXu** [quickwit-inc/tantivy#2262]
I want to integrate tantivy into a database system. the database is written by C++, so I use FFI to call tantivy.
But recently I get a problem, when I call IndexWriter commit function, and free IndexWriter(use Drop trait), my C++ program will list the index files and processing them to a single file, when processing these index files, some file may missing, I guess that `garbage_collect_files` may still work after IndexWriter been dropped.

**Comment by PSeitz** [comment]
Do you deactivate background merges by setting `NoMergePolicy` on  the `IndexWriter`? 

```rust
index_writer.set_merge_policy(Box::new(NoMergePolicy));
```

**Comment by MochiXu** [comment]
@PSeitz Thank you! I have solved this problem by calling `wait_merging_threads` method to deactivate all merging threads.
