### ISSUE TITLE
Token Payloads

### ISSUE THREAD

**Issue by knpwrs** [quickwit-inc/tantivy#2263]
Is it possible to store payloads with individual tokens in Tantivy? For instance, in ElasticSearch if you use the [Delimited payload token filter](https://github.com/elastic/elasticsearch/edit/8.11/docs/reference/analysis/tokenfilters/delimited-payload-tokenfilter.asciidoc) it is possible to index a document where each individual token is associated with a number payload (e.g., a timestamp for a transcript).

**Comment by fulmicoton** [comment]
This is not possible.

**Comment by knpwrs** [comment]
Okay, thank you. I do have a follow-up question: would there be any way to store an array of objects (like `[{ word: 'word', payload: 3 }, { word: 'foo', payload: 4 }]` and search that array in an order-dependant way? Searching for records matching `[{ word: 'word' }, { word: 'foo' }]` would match that record, but `[{ word: 'foo' }, { word: 'word' }]` should not.

**Comment by fulmicoton** [comment]
This is not possible either.
