### ISSUE TITLE
parsing range query with whitespace fails on `0.21` but not `0.20`

### ISSUE THREAD

**Issue by ljeub-pometry** [quickwit-inc/tantivy#2289]
Whitespace in a range query causes a `SyntaxError` on `0.21` but was parsed just fine in `0.20`. 

Consider this example:

```rust
use tantivy::query::QueryParser;
use tantivy::schema::{FAST, INDEXED, Schema, STORED};
use tantivy::tokenizer::TokenizerManager;

fn main() {
    let mut schema = Schema::builder();
    schema.add_u64_field("num", INDEXED | STORED | FAST);
    let query_parser = QueryParser::new(schema.build(), vec![], TokenizerManager::default());
    let query = query_parser.parse_query("num: [0 TO 10]").unwrap();
    println!("{query:?}")
}
```
on version `0.21` this results in
```
thread 'main' panicked at src/main.rs:11:60:
called `Result::unwrap()` on an `Err` value: SyntaxError("num: [0 TO 10]")
```

whereas on version `0.20` this prints
```
RangeQuery { field: "num", value_type: U64, lower_bound: Included([0, 0, 0, 0, 0, 0, 0, 0]), upper_bound: Included([0, 0, 0, 0, 0, 0, 0, 10]), limit: None }
```

**Which version of tantivy are you using?**
`0.21.1`

**To Reproduce**

See example above

**Comment by fulmicoton** [comment]
Regression are bad, but  I am not sure we want to accept spaces there. @trinity-1686a what do you think?

**Comment by trinity-1686a** [comment]
I don't think we should accept spaces here either, at least on the strict parser side. Afaict no test/example/documentation ever said it works (and I'm surprised to learn that it did).
It should already be working on the lenient parser side, where we are less regarding on respecting a strict syntax

**Comment by fulmicoton** [comment]
Closing then... @ljeub-pometry if you need it you can try and use the lenient mode.

**Comment by ljeub-pometry** [comment]
I already removed the whitespace on our internal queries so not a big problem. Just came as a bit of a surprise after updating the dependency version and a bunch of tests failed because of this . 

These tests were together with a bunch of `field: IN [A B]` queries which is probably where the idea of the whitespace there came from as it is indeed not in the documentation for the range queries.
