### ISSUE TITLE
Potential to modify ordering for state in file_watcher model

### ISSUE THREAD

**Issue by wang384670111** [quickwit-inc/tantivy#2292]
I think that the `state` synchronizes with the `callbacks`.
https://github.com/quickwit-oss/tantivy/blob/53f2fe1fbee83f22c81e28aaec02fb0628b68966/src/directory/file_watcher.rs#L15-L19
The `compare_exchange` at 33 should use `AcqRel` to guarantee visibility of changes to the `callbacks` and to fetch the most recent `callbacks` in the success case at 40. In the failure case, `Relaxed` can be used since it merely involves a state check. The `load` at 48, being a state check, is sufficient with Relaxed, as the `compare_exchange` at 33 ensures that `callbacks` are up to date. Lastly, the `write` on line 95 needs to use `Release` to properly update the callbacks.
https://github.com/quickwit-oss/tantivy/blob/53f2fe1fbee83f22c81e28aaec02fb0628b68966/src/directory/file_watcher.rs#L31-L37
https://github.com/quickwit-oss/tantivy/blob/53f2fe1fbee83f22c81e28aaec02fb0628b68966/src/directory/file_watcher.rs#L48
https://github.com/quickwit-oss/tantivy/blob/53f2fe1fbee83f22c81e28aaec02fb0628b68966/src/directory/file_watcher.rs#L95

(happy to make a PR if this looks reasonable)

**Comment by adamreichold** [comment]
Independently of the analysis being correct or not, have you measured any performance change due to this? Even on a weakly ordered machine like aarch64? I don't think this code is on any hot path.

**Comment by adamreichold** [comment]
(Or put differently, I think the greatest efficiency change here would be going from polling to using something like the [`notify` crate](https://lib.rs/crates/notify) to perform the work only when the underlying filesystem has actually changed.)

**Comment by wang384670111** [comment]
> Independently of the analysis being correct or not, have you measured any performance change due to this? Even on a weakly ordered machine like aarch64? I don't think this code is on any hot path. 

In my x86 and arm64 experiments with different ordering options, performance disparities were evident, particularly in high-concurrency situations. The performance gap was less pronounced in low-concurrency scenarios. However, it's worth noting that the observed trends may not be directly applicable to this specific crate. Nevertheless, the consensus remains that employing seqcst is often unnecessary in many scenarios, making it suboptimal as a programming practice.

**Comment by adamreichold** [comment]
I don't mean generally, but specifically for this piece of code. Have you done any measurements of the effects of the proposed changes?

**Comment by fulmicoton** [comment]
It won't make any difference, so it is not worth overthinking this.
