### ISSUE TITLE
How can I trigger a search with a minimum character count?

### ISSUE THREAD

**Issue by billywatkins** [quickwit-inc/tantivy#2297]
Currently, Tantivy provides search results when the query has at least 4 characters. However, I want to trigger the search even with just one character. I found something called MoreLikeThisQuery in the documentation, but I am still unable to figure out how to use it.

https://teaclave.apache.org/api-docs/crates-enclave/tantivy/query/struct.MoreLikeThisQuery.html

**Comment by PSeitz** [comment]
Which 4 character limit are you referring to?

**Comment by billywatkins** [comment]
Hey, sorry. I should have been more clear. I wanted something similar to how HN search works at https://hn.algolia.com/.

If there is "Apple is red," then tantivy should retrieve it not only when the query is "Apple" but also when I type "A"

**Comment by PSeitz** [comment]
You can use [PhrasePrefixQuery](https://docs.rs/tantivy/latest/tantivy/query/struct.PhrasePrefixQuery.html)  or [FuzzyTermQuery with prefix](https://docs.rs/tantivy/latest/tantivy/query/struct.FuzzyTermQuery.html#method.new_prefix) 

Example:
https://github.com/quickwit-oss/tantivy/blob/main/examples/phrase_prefix_search.rs

**Comment by billywatkins** [comment]
Thanks, it worked for one field, but when I try prefix queries on multiple fields, it throws an error: 'All terms from a phrase query must belong to the same field.'

Is this possible, or am I doing something wrong?

```rust
    let field1 = Term::from_field_text(schema_config.field1, &query);
    let field2 = Term::from_field_text(schema_config.field2, &query);
  
    let phrase_query = PhrasePrefixQuery::new(vec![
    field1,
    field2
    ]);
```

**Comment by PSeitz** [comment]
You need to combine different fields into a [BooleanQuery](https://docs.rs/tantivy/latest/tantivy/query/struct.BooleanQuery.html)

**Comment by billywatkins** [comment]
It worked thank you so much!
