### ISSUE TITLE
How to deal with undesirable stemming?

### ISSUE THREAD

**Issue by kornelski** [quickwit-inc/tantivy#2329]
The `rust_stemmers` crate unifies two words that in Rust's context have a very different meaning:

```rust
assert_eq!(en_stemmer.stem("international"), en_stemmer.stem("internal"));
assert_eq!(en_stemmer.stem("interning"), en_stemmer.stem("internal"));
```

Which gives very poor search results for "string interning", because instead of specific libraries for interning, it just brings lots of vaguely string-related crates: https://lib.rs/search?q=string%20interning

Does tantivy have anything to deal with such cases?

The best I can think of is duplicating text fields into fields with stemming and without stemming, and giving them different weights. Does tantivy do something like that internally already?

**Comment by kornelski** [comment]
I wrote a custom stemmer.

**Comment by fulmicoton** [comment]
Another common solution to the problem is to index the token twice. Once with stemming the other without stemming.
Right now unfortunately, tantivy does not give you the tool to do that appropriately.

You would want your tokenizer to operate asymetrically on indexing and querying.

**Comment by kornelski** [comment]
Yes, indeed, asymmetrically handling tokens would be quite helpful. I have a table of synonyms, and for indexing I'd like to store multiple versions of a word, but for querying I'd like query to match if it matches any of the words in the group of synonyms (`word OR synonym`), rather than require all of them (`word AND synonym`).
