### ISSUE TITLE
Regular Expression Queries

### ISSUE THREAD

**Issue by inzanez** [quickwit-inc/tantivy#2355]
Hi

is it possible that `RegexQuery` does not support whitespaces? I was investigating how I would handle search for things like

* "term1* AND (term2 OR term3 OR term4)"
* term1* AND (term2* OR term3)

All in all it seems that I cannot simply convert that into a regular expression query,...so I would need to create a regular expression query and combine that with other queries,...

But even if I combine queries that way,...how would I search for something like this?
"term1* term2" AND (term3)

**Comment by fulmicoton** [comment]
This is not supported no.
