### ISSUE TITLE
Negative Term 

### ISSUE THREAD

**Issue by inzanez** [quickwit-inc/tantivy#2357]
Building an index and running a search like:
`apple -fruit`

always returns `Invalid query: Only excluding terms given`.

But `apple` is definitely not an excluding term. Maybe I misunderstand something here.

**Comment by PSeitz** [comment]
Can you give an reproducible example?

**Comment by inzanez** [comment]
Ignore that, somehow I stripped the positive term and I have just seen that only negative terms do not work and the "match all" term is required,...
