### ISSUE TITLE
Questions about the details of how Tantivy manages index files.

### ISSUE THREAD

**Issue by MochiXu** [quickwit-inc/tantivy#2373]
Hello,

I would like to understand the details of how Tantivy manages index files (.fast, .fieldnorm, .idx, .pos, .term). I am using Rust FFI in C++ to call Tantivy-related functions, and I have a use case where I need to index a large amount of data using Tantivy. After Tantivy generates a set of segments index files, I use my own serialization code to serialize these files (several dozen) into a single file. When I need to use these Tantivy files, I use my own deserialization logic to restore them, so that Tantivy can load the index and perform text searching on these restored index files.

I have found that when the amount of data is relatively small, such as only 5 million rows of text data needing to be indexed, the existing code logic can run normally. However, when there are 20 million rows of text data, I have discovered that the code will run into errors. After deserializing and restoring the index files, Tantivy considers the restored files to be erroneous.
Here is ERROR log:
```
2024.04.24 15:54:10.043886 [ 375 ] {e01298d2-3ce3-4aef-a0a5-bf28a9acf140} <Error> TantivyLibrary: [92] - [tantivy_search: load_index_reader] - Data corrupted: 'Data corruption (in file `".managed.json"`): Managed file cannot be deserialized: Error("expected value", line: 1, column: 1). .'
2024.04.24 15:54:10.044443 [ 375 ] {e01298d2-3ce3-4aef-a0a5-bf28a9acf140} <Error> TantivyLibrary: [92] - [tantivy_search: ffi_load_index_reader] - Error loading index reader: Data corrupted: 'Data corruption (in file `".managed.json"`): Managed file cannot be deserialized: Error("expected value", line: 1, column: 1). .'
```

I personally suspect that when I perform serialization in the C++ code, Tantivy is still updating the index files (merging or some other operations). Currently, before serializing the index files in C++, I always call Tantivy's `wait_merging_threads` function, but I am not sure how to ensure that Tantivy will not make any further modifications to the index files.

Could you please provide some valuable suggestions? Thank you very much.

**Comment by PSeitz** [comment]
To avoid merges to intersect with your serialization logic, it's probably best if you disable them via the `NoMergePolicy` and handle them yourself or implement you own `MergePolicy`

Otherwise, this looks like there's an error in your serialization logic.

Existing index files are not updated btw., they are immutable. Only the metadata files are updated. `.managed.json` and `meta.json`

**Comment by MochiXu** [comment]
Thanks for reminding me that existing index files are not updated; only the metadata files are updated.
