### ISSUE TITLE
Store DateTime as nanos in docstore

### ISSUE THREAD

**Issue by trinity-1686a** [quickwit-inc/tantivy#2380]
we use `BinarySerializable` to encode datetimes into the doc store. Strangely, while DateTime are precise up to ns, we only store µs there. We should store the value we got with full precision instead 
https://github.com/quickwit-oss/tantivy/blob/99a59ad37e833e1129f7e1abd25738a0adfae73a/common/src/datetime.rs#L166-L176

**Comment by fulmicoton** [comment]
We need to be careful with backward compatiblity with that one. 

Is it motivated by a problem observed on quickwit side? Is there a ticket open somewhere?

**Comment by trinity-1686a** [comment]
it was observed that when asked to return nanoseconds, quickwit returns values truncated to microsecond precision. This is surprising, and potentially problematic for use-cases relying on high precision timestamps
