### ISSUE TITLE
Implement "minimum number should match" on BooleanQuery

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/tantivy#2398]
In a booleanquery, it can be useful to indicate that we want any 2 out of 3 terms to match.
In lucene, this is possible by setting https://lucene.apache.org/core/6_1_0/core/org/apache/lucene/search/BooleanQuery.Builder.html#setMinimumNumberShouldMatch-int-

Regardless of the implementation, it will need to have no impact over the performance of the existing union queries.

**Comment by LebranceBW** [comment]
I'm willing to implement this feature. However, my familiarity with this project is limited. Here are my initial considerations:

* The `minimum_should_match` functionality operates as an additional constraint on BooleanQuery. It appears that the existing  [`UnionScorer`] cannot fit it.  A novel scorer `MinimumRequirementScorer` based on [`UnionScorer`] needs to be developed, which rejects `Doc`  missing conditions. `minimum_should_match` will be passed as one of it's member.
* To minimize performance impacts, the `MinimumRequirementScorer`, 
[`UnionScorer`], and [`RequiredOptionalScorer`] will be employed under different `BooleanQuery` combinations.

Advices wanted. 😄 

[`UnionScorer`]: https://github.com/quickwit-oss/tantivy/blob/5b7cca13e5136c7e3b86f645be38b08bed2d6f78/src/query/union.rs#L29
[`RequiredOptionalScorer`]: https://github.com/quickwit-oss/tantivy/blob/5b7cca13e5136c7e3b86f645be38b08bed2d6f78/src/query/reqopt_scorer.rs#L15

**Comment by fulmicoton** [comment]
@LebranceBW I agree with both points. 

The `BooleanQuery -> BooleanWeight -> BooleanScorer` are precisely here so that while users define their query by instanting  a `Query` object, this query can be at runtime converted into different `Scorer`.

**Comment by PSeitz** [comment]
Thanks @LebranceBW  https://github.com/quickwit-oss/tantivy/pull/2405
