### ISSUE TITLE
Does tantivy::IndexWriter support multi-process?

### ISSUE THREAD

**Issue by cyccbxhl** [quickwit-inc/tantivy#2408]
I'm considering an integration of Tantivy with PostgreSQL, which has a multi-process architecture where each insert/update/delete/vacuum operation is handled by a separate process. However, Tantivy's IndexWriter cannot be initialized simultaneously by multiple processes in the same directory due to the INDEX_WRITER_LOCK.

To enable concurrent insert/delete operations, I'm thinking of removing the INDEX_WRITER_LOCK when initializing the tantivy::IndexWriter within the PostgreSQL insert backend process. Instead, I plan to introduce a read-write lock located in shared memory. This lock would be acquired as a read lock during add_document/delete_term operations and as a write lock during commit operations (the garbage collection process would also acquire a write lock).

Would this approach violate any internal implementation contracts of Tantivy, and is it feasible?

I'm looking for guidance on whether this strategy could potentially disrupt Tantivy's internal mechanisms and whether it aligns with Tantivy's design principles.

**Comment by fulmicoton** [comment]
> Would this approach violate any internal implementation contracts of Tantivy, and is it feasible?

It will most likely not work yes.

The problem has to do with the delete and commit work.
Deletes are performed right before serialization.

The reason something like 
```
 - add_doc(1)
 - delete_doc(1)
 - delete_doc(2)
 - add_doc(2)
```
work the way you expect, is because we attach an opstamp to each document and each delete operation, to know in which order those operations happened.

With your scheme, two concurrent writes could end up with very different outcomes.


```thread one
 - add_doc(1)
 - add_doc(2)
```

```thread two
 - delete_doc(1)
 - delete_doc(2)
```

You could end up with 
no docs, doc1, doc2, doc1 and doc2 in the resulting tantivy index.

It will NOT look like the transaction were executed in the order of them taking the write lock.

**Comment by cyccbxhl** [comment]
> Deletes are performed right before serialization.
Cloud you explain more about it?
I don't need tantivy's operation executed in the order of them taking the write lock, but I need them to meet the RC (Read Committed) isolation level: Only committed data is visible for other transaction.
(tantivy's commit would be called in pg's commit command.)

For your example:
             txn1                             txn2
t1          pg's begin;
t2         add_doc(1);                pg's begin;
t3                                             delete_doc(1);
t4         add_doc(2);
t5                                             delete_doc(2);
t6         pg's commit;
t7                                              pg's commit;

The behavior I expect:
(1) According to the sequence diagram of operations above,  doc 1 and doc2 would be invisible for delete ops in txn2, and I need there are doc1 and doc2 in the resulting tantivy index.
(2) If txn1's commit is before than txn2's delete ops, there would be no doc in the resulting tantivy index.
Can tantivy be able to do that?

**Comment by cyccbxhl** [comment]
>> The problem has to do with the delete and commit work. Deletes are performed right before serialization.


Can you explain more about it?

Tantivy's commit would be called in pg's commit command, I actually don't need tantivy operations executed in the order of them taking the write lock, I need them meet the RC(Read Committed) transaction isolation level: Only committed operation/data is visible for other concurrent transaction.
The behavior I expect:
(1)
<img width="763" alt="image" src="https://github.com/quickwit-oss/tantivy/assets/9246255/0aad1c63-86a5-4f5d-a726-4b553d8e6cf0">
Because the doc1 and doc2 is invisible for delete ops in txn2, when txn1 and txn2 all committed, there are doc1 and doc2 in the resulting tantivy index;
(2)
<img width="742" alt="image" src="https://github.com/quickwit-oss/tantivy/assets/9246255/2fe4441e-387b-477f-84f4-4e8c36d3c21e">
when txn1 and txn2 all committed, there are no doc in the resulting tantivy index;

Can tantivy be able to do that?

**Comment by fulmicoton** [comment]
Actually I think you are right it might work.

**Comment by cyccbxhl** [comment]
Thank you very much. I'll try implementing the code based on this plan first to see if there are any other issues. There might be some questions I will need to ask you later. I will close this issue for now.
