### ISSUE TITLE
on android: OS error 38 - function not implemented

### ISSUE THREAD

**Issue by Sivan22** [quickwit-inc/tantivy#2480]
**Describe the bug**
i am using the library in my flutter app, through flutter_rust_bridge. it compiles and runs, but when trying to search i get the following error: ` Error: PanicException(Failed to create index reader: LockFailure(loError(Os {code:38, kind:Unsupported,message:"Function not implemented"}),None))
`

**Which version of tantivy are you using?**
0.22.0

**To Reproduce**

* clone https://github.com/Sivan22/otzaria and https://github.com/Sivan22/otzaria_search_engine to the same folder.
* ` cd otzaria `
* ` flutter run android`
* in the app, try searching

**Comment by PSeitz** [comment]
This is probably related to directory locking. What `Directory` implementation do you use?

**Comment by Sivan22** [comment]
`use tantivy::directory::MmapDirectory`


`let mmap_directory = MmapDirectory::open(path).expect("unable to open mmap directory");
        let index = Index::open_or_create(mmap_directory, schema.clone());
        let index = index.expect("Failed to create index").clone();
        let index_reader = index.reader().expect("Failed to create index reader");
`

**Comment by Sivan22** [comment]
So my question is: what is status of supporting Mmap Directory on android? (the RamDirectory works as expected)

**Comment by fulmicoton** [comment]
It is not supported
