### ISSUE TITLE
Add `CITATION.cff` to make it easy to cite this in papers

### ISSUE THREAD

**Issue by jamesbraza** [quickwit-inc/tantivy#2521]
**Is your feature request related to a problem? Please describe.**

I would like to cite `tantivy` as we use its Python bindings in https://github.com/Future-House/paper-qa.

GitHub supports making it easy to cite repositories using `CITATION.cff`: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

**Describe the solution you'd like**

Can `tantivy` add a `CITATION.cff`?

**[Optional] describe alternatives you've considered**

N/a

**Comment by fulmicoton** [comment]
I added a CITATION.cff file.

**Comment by jamesbraza** [comment]
Thanks for the quick turnaround Paul. The dropdown though isn't working though, and using https://github.com/citation-file-format/cffconvert I think it's because you got the `authors` wrong, it should be a `list` not a `dict`:

Running `cffconvert --validate --url https://github.com/quickwit-oss/tantivy`:

```none
jsonschema.exceptions.ValidationError: {'alias': 'Quickwit Inc.', 'website': 'https://quickwit.io'} is not of type 'array'

Failed validating 'type' in schema['properties']['authors']:
    {'description': 'The author(s) of the software or dataset.',
     'items': {'anyOf': [{'$ref': '#/definitions/person'},
                         {'$ref': '#/definitions/entity'}]},
     'minItems': 1,
     'type': 'array',
     'uniqueItems': True}

On instance['authors']:
    {'alias': 'Quickwit Inc.', 'website': 'https://quickwit.io'}
```

**Comment by fulmicoton** [comment]
fixed

**Comment by jamesbraza** [comment]
Nice it works now, thank you! 🙏
