### ISSUE TITLE
Why `panic!` when field exists on add_field?

### ISSUE THREAD

**Issue by zarkone** [quickwit-inc/tantivy#2529]
https://github.com/quickwit-oss/tantivy/blob/f9ac055847b82cc2010c3d43de07d014b82513c3/src/schema/schema.rs#L202

I wonder why not return Result instead? 

I understand that it might require a lot of adjustments at this point, but decide to ask just in case if there was a particular reason to do it via panic.

Thanks!

**Comment by fulmicoton** [comment]
Legacy mostly. I am not entirely sure whether we would do it that way or not today.
