### ISSUE TITLE
Hardcoded `NUM_MERGE_THREADS`

### ISSUE THREAD

**Issue by Barre** [quickwit-inc/tantivy#2533]
Hello,

I am trying to index a few billions documents.
In my usecase, the bottleneck seems to be the number of merging threads which seems to be hardcoded here: https://github.com/quickwit-oss/tantivy/blob/main/src/indexer/segment_updater.rs#L28

Would you be open to a PR that makes this configurable?

**Comment by PSeitz** [comment]
Yes, that could be configurable

**Comment by fulmicoton** [comment]
agreed.
