### ISSUE TITLE
RUSTSEC-2024-0384: Unmaintained transitive dependency

### ISSUE THREAD

**Issue by turmanticant** [quickwit-inc/tantivy#2554]
**Describe the bug**

Hey! I use cargo-deny and noticed I was getting an error for one of tantivys transitive dependencies.

[measure_time](https://github.com/PSeitz/rust_measure_time) depends on [instant](https://github.com/sebcrozet/instant) which has been marked as unmaintained. There is no security vuln associated or anything requiring immediate action as best as I could tell.

There is only one place in tantivy I could see that uses `measure_time`, [src/indexer/merger.rs](https://github.com/quickwit-oss/tantivy/blob/876a579e5da1223b40df044be396faac8151ff91/src/indexer/merger.rs#L8).

It is importing the `debug_time` macro and using it to instrument a few methods.
```rust
        debug_time!("write-fast-fields");
```

Given the small usage here, could this replaced with a `log::debug!` and remove the dependency to `measure_time`? If so, I'm happy to open a PR doing that. :grinning: 

Advisory:
https://rustsec.org/advisories/RUSTSEC-2024-0384

**Which version of tantivy are you using?**
0.22

**To Reproduce**
```shell
cargo deny check
```

**Comment by fulmicoton** [comment]
@PSeitz can you have a look?
