### ISSUE TITLE
Boolean Query between fields

### ISSUE THREAD

**Issue by rconnol** [quickwit-inc/tantivy#2560]
Try to be specific about your use case...

Is it possible to create a BooleanQuery that compares two existing fields in an index?

so for example, if I have a field called `entity_id` - and I have another field called `entity_id_action`. I want to select all of the documents where `entity_id` does not equal `entity_id_action`. Is that currently possible? it looks like all boolean queries are based on values that are passed in and cannot be "other fields".

additionally, it is it possible to have an aggregation with a boolean query as the metric?

so for example, I would like to return the count of documents that match my condition - `entity_id` does not equal `entity_action_id`. Is that currently possible?

**Comment by fulmicoton** [comment]
This is not possible today.
